import { describe,expect,it } from 'vitest'
import type { SchoolRecord } from '../scorecard/schema'
import { calculatePlannerSchool,createPlannerSchoolPlan,createPlannerSharedState,type PlannerSchoolPlan,type PlannerSharedState,type PlannerTransition } from './plannerAdapter'

const school:SchoolRecord={unitId:123456,name:'Planner University',state:'OH',control:'public',costOfAttendance:30_000,tuitionInState:12_000,tuitionOutOfState:24_000,averageNetPrice:18_000,averageNetPriceByIncome:{'0-30000':null,'30001-48000':null,'48001-75000':null,'75001-110000':null,'110001-plus':null},graduationRate:.7,medianFederalDebtAtGraduation:20_000,earnings:[],fieldOfStudyEarnings:[],dataYear:'2023'}
const knownZero={status:'known' as const,amount:0,explanation:'',source:'Confirmed by user'}
const notApplicablePredicates:PlannerTransition['predicates']={enrolledInProgramAtInstitutionOn2026_06_30:false,qualifyingDirectLoanDisbursedBefore2026_07_01:false,qualifyingLoanRecipient:'student',qualifyingLoanCanceled:false,remainsEnrolledInSameProgram:false,withdrewOrOtherwiseCeasedEnrollment:false,approvedTitleIvLeaveOfAbsence:false,returnedToSameProgramWithinApprovedLeaveWindow:false,withinInstitutionDeterminedExpectedTimeToCredential:false}
const applicablePredicates:PlannerTransition['predicates']={enrolledInProgramAtInstitutionOn2026_06_30:true,qualifyingDirectLoanDisbursedBefore2026_07_01:true,qualifyingLoanRecipient:'student',qualifyingLoanCanceled:false,remainsEnrolledInSameProgram:true,withdrewOrOtherwiseCeasedEnrollment:false,approvedTitleIvLeaveOfAbsence:false,returnedToSameProgramWithinApprovedLeaveWindow:false,withinInstitutionDeterminedExpectedTimeToCredential:true}
function ready(){
  const plan=createPlannerSchoolPlan(school,5_325),shared=createPlannerSharedState('dependent')
  plan.educationLevel='undergraduate';plan.enrollmentPattern='full_time_standard_academic_year';plan.programIdentifier='BA-TEST';plan.programScope='supported'
  plan.funding={grant:{...knownZero,schedule:'recurring',year:1},scholarship:{...knownZero,schedule:'recurring',year:1},otherGrant:{...knownZero,schedule:'recurring',year:1},familyCash:{...knownZero,schedule:'recurring',year:1}}
  plan.pell=plan.pell.map((fact,index)=>index?{...knownZero}:{...fact})
  plan.gradeLevels=[1,2,3,4,4];plan.academicYearStarts=['2026-07-01','2027-07-01','2028-07-01','2029-07-01','2030-07-01'];plan.enrollmentPeriodStarts=[...plan.academicYearStarts]
  plan.higherLimits=plan.higherLimits.map(()=>({status:'not_qualified',basis:'verified_parent_plus_denial',reason:'no_qualifying_determination'}))
  plan.transition=plan.academicYearStarts.map(date=>({status:'verified_not_applicable',institutionIdentifier:String(school.unitId),programIdentifier:plan.programIdentifier,enrollmentPeriodStart:date,predicates:{...notApplicablePredicates}}))
  plan.institutionalStatus='none_confirmed';plan.disbursementDates=['2026-08-15','2027-08-15','2028-08-15','2029-08-15','2030-08-15'];plan.disbursementAssumptionAccepted=true
  shared.history={status:'confirmed_complete',directOutstanding:0,subsidizedOutstanding:0,lifetimeDirectAndFfel:0,lifetimeGraduatePlus:0,parentPlusBorrowedAsParentExcluded:0,healExcluded:0,convertedTeachGrant:0,consolidationUnderlyingIncluded:true,parentPlusAggregate:0,currentYearDirect:[0,0,0,0,0],currentYearSubsidized:[0,0,0,0,0],currentYearParentPlus:[0,0,0,0,0]}
  shared.graduationDate='2030-05-15';shared.subsidyEnrollment='qualifying_in_school';shared.noInSchoolPaymentsAccepted=true
  return {plan,shared}
}
const result=(plan:PlannerSchoolPlan,shared:PlannerSharedState)=>calculatePlannerSchool(school,plan,shared)

describe('pure planner adapter',()=>{
  it('starts optional cost components, non-loan funding, and institutional restrictions unknown',()=>{const plan=createPlannerSchoolPlan(school,5_325);expect(plan.components.housing.status).toBe('unknown');expect(plan.components.books.status).toBe('unknown');expect(plan.funding.grant.status).toBe('unknown');expect(plan.funding.familyCash.status).toBe('unknown');expect(plan.institutionalStatus).toBe('unknown');expect(plan.disbursementDates.every(x=>x==='')).toBe(true)})
  it.each([['missing','incomplete'],['independent','unsupported']] as const)('fails closed for %s profile scope',(scope,status)=>{const {plan,shared}=ready();shared.dependencyStatus=scope;expect(result(plan,shared).status).toBe(status)})
  it.each([['part_time','unsupported'],['summer_or_nonstandard','unsupported']] as const)('fails closed for %s enrollment',(scope,status)=>{const {plan,shared}=ready();plan.enrollmentPattern=scope;expect(result(plan,shared).status).toBe(status)})
  it('fails closed for an unsupported program structure',()=>{const {plan,shared}=ready();plan.programScope='unsupported';expect(result(plan,shared).status).toBe('unsupported')})
  it('fails closed when program or grade is unresolved',()=>{const {plan,shared}=ready();plan.programIdentifier='';plan.gradeLevels[0]=null;const value=result(plan,shared);expect(value.allocations[0].status).toBe('incomplete');expect(value.missingReasons.join(' ')).toMatch(/program identifier|grade level/i)})
  it('keeps a complete four-year cost when future Pell is unknown',()=>{const {plan,shared}=ready();plan.pell.slice(1).forEach(fact=>{fact.status='unknown'});const value=result(plan,shared);expect(value.metrics.cost).toMatchObject({status:'complete',knownCents:12_000_000,resolvedYears:4});expect(value.metrics.grants.status).toBe('partial');expect(value.metrics.gap.status).toBe('partial')})
  it('labels known-subset totals partial rather than complete',()=>{const {plan,shared}=ready();plan.funding.grant.schedule='custom_year';plan.funding.grant.year=5;shared.horizon=4;const value=result(plan,shared);expect(value.errors.some(x=>x.field==='funding-grant-year')).toBe(true)})
  it('accepts nonzero Direct, subsidized, lifetime, current-year, Parent PLUS, and consolidation history',()=>{const {plan,shared}=ready();Object.assign(shared.history,{directOutstanding:20_000,subsidizedOutstanding:10_000,lifetimeDirectAndFfel:25_000,parentPlusAggregate:20_000});shared.history.currentYearDirect[0]=500;shared.history.currentYearSubsidized[0]=250;shared.history.currentYearParentPlus[0]=500;plan.subsidizedGross[0]=1_000;const value=result(plan,shared);expect(value.allocations[0].status).toBe('complete')})
  it('does not roll a failed Year 1 election into Year 2 history',()=>{const {plan,shared}=ready();Object.assign(shared.history,{directOutstanding:25_000,subsidizedOutstanding:0});plan.subsidizedGross[0]=5_501;plan.unsubsidizedGross[1]=6_000;const value=result(plan,shared);expect(value.allocations[0].status).toBe('exceeds_limit');expect(value.allocations[1].status).toBe('complete')})
  it.each(['qualified','not_qualified','unresolved','stale'] as const)('preserves higher-limit determination %s',(status)=>{const {plan,shared}=ready();plan.higherLimits[0].status=status;const value=result(plan,shared);expect(value.allocations[0].status).toBe(status==='qualified'||status==='not_qualified'?'complete':'incomplete')})
  it('does not turn a Parent PLUS denial into higher-limit qualification',()=>{const {plan,shared}=ready();plan.parentCredit='denied';plan.parentPlusGross[0]=1_000;plan.higherLimits[0].status='unresolved';const value=result(plan,shared);expect(value.allocations[0].status).toBe('incomplete');expect(value.missingReasons.join(' ')).toMatch(/higher-limit/i)})
  it('supports verified-applicable transition evidence bound to the selected school, program, period, and explicit predicates',()=>{const {plan,shared}=ready();plan.transition[0].status='verified_applicable';plan.transition[0].predicates={...applicablePredicates};const value=result(plan,shared);expect(value.allocations[0].status).toBe('complete')})
  it('fails closed when a verified transition predicate remains unresolved',()=>{const {plan,shared}=ready();plan.transition[0].predicates.qualifyingLoanCanceled=null;const value=result(plan,shared);expect(value.allocations[0].status).toBe('incomplete');expect(value.missingReasons.join(' ')).toMatch(/predicate.*explicitly resolved/i)})
  it.each([['institutionIdentifier','999999'],['programIdentifier','OTHER'],['enrollmentPeriodStart','2025-07-01']] as const)('rejects transition evidence with wrong %s',(key,bad)=>{const {plan,shared}=ready();plan.transition[0].status='verified_applicable';plan.transition[0].predicates={...applicablePredicates};plan.transition[0][key]=bad;const value=result(plan,shared);expect(value.allocations[0].status).toBe('incomplete');expect(value.allocations[0].status==='complete'?'':value.allocations[0].reasons.join(' ')).toMatch(/does not match/i)})
  it('requires explicit graduation, subsidy enrollment, and no-payment facts',()=>{const {plan,shared}=ready();shared.graduationDate='';shared.subsidyEnrollment='unresolved';shared.noInSchoolPaymentsAccepted=false;const value=result(plan,shared);expect(value.graduation).toBeNull();expect(value.metrics.studentDebt.status).toBe('incomplete')})
  it('represents a legitimate $0 annual cost override explicitly',()=>{const {plan,shared}=ready();plan.overrides[0]={enabled:true,amount:0,explanation:'Confirmed tuition waiver and no living costs'};const value=result(plan,shared);expect(value.funding?.annual[0].projectedCostCents).toBe(0)})
  it('returns typed validation errors instead of throwing for invalid growth, rates, and explanations',()=>{const {plan,shared}=ready();shared.growthMode='percentage';shared.growth=101;shared.futureRates[0]=101;plan.totalCost={status:'assumed',amount:30_000,explanation:'',source:'User'};expect(()=>result(plan,shared)).not.toThrow();const value=result(plan,shared);expect(value.status).toBe('error');expect(value.errors.map(x=>x.field)).toEqual(expect.arrayContaining(['growth','futureRate-0','totalCost-explanation']))})
  it('ignores an out-of-horizon Year 5 custom schedule after switching to four years',()=>{const {plan,shared}=ready();shared.horizon=5;plan.funding.grant.schedule='custom_year';plan.funding.grant.year=5;shared.horizon=4;expect(()=>result(plan,shared)).not.toThrow();expect(result(plan,shared).errors.some(x=>x.field==='funding-grant-year')).toBe(true)})
  it('surfaces requested and allowed values on a federal limit failure',()=>{const {plan,shared}=ready();plan.subsidizedGross[0]=6_000;const allocation=result(plan,shared).allocations[0];expect(allocation.status).toBe('exceeds_limit');if(allocation.status==='exceeds_limit'){expect(allocation.requested?.combinedCents).toBe(600_000);expect(allocation.allowed?.combinedCents).toBe(550_000)}})
  it('preserves known Pell when other grant categories remain unknown',()=>{const {plan,shared}=ready();plan.funding.grant.status='unknown';plan.funding.scholarship.status='unknown';const value=result(plan,shared);expect(value.metrics.grants).toMatchObject({status:'partial',knownCents:532_500});expect(value.metrics.grants.reasons.join(' ')).toMatch(/Institutional grant|Outside scholarship/)} )
  it('keeps surplus distinct from a clamped remaining gap and preserves known partial surplus',()=>{const {plan,shared}=ready();plan.totalCost={status:'known',amount:1_000,explanation:'',source:'confirmed'};plan.funding.familyCash={...knownZero,amount:1_000,schedule:'recurring',year:1};plan.unsubsidizedGross[0]=2_000;let value=result(plan,shared);expect(value.metrics.gap).toMatchObject({status:'complete',knownCents:0});expect(value.metrics.surplus).toMatchObject({status:'complete',knownCents:197_886});plan.subsidizedGross[1]=6_000;value=result(plan,shared);expect(value.metrics.surplus).toMatchObject({status:'partial',knownCents:197_886});expect(value.metrics.surplus.knownCents).toBeDefined()})
  it('does not roll a failed Parent PLUS election into later Parent PLUS history',()=>{const {plan,shared}=ready();shared.history.parentPlusAggregate=45_000;plan.parentCredit='eligible';plan.parentPlusGross[0]=20_001;plan.parentPlusGross[1]=20_000;const value=result(plan,shared);expect(value.allocations[0].status).toBe('exceeds_limit');expect(value.allocations[1].status).toBe('complete')})
  it.each([
    ['academicYearStarts',0,'academicYearStart-0'],
    ['enrollmentPeriodStarts',0,'enrollmentPeriodStart-0'],
    ['disbursementDates',0,'disbursementDate-0'],
  ] as const)('returns a typed error without a fabricated fallback for malformed %s',(key,index,field)=>{const {plan,shared}=ready();plan[key][index]='2026-02-30';const value=result(plan,shared);expect(value.errors).toEqual(expect.arrayContaining([expect.objectContaining({field,message:'Enter a valid calendar date in YYYY-MM-DD format.'})]))})
  it('returns a typed error without a fabricated fallback for a malformed graduation date',()=>{const {plan,shared}=ready();shared.graduationDate='2030-02-30';const value=result(plan,shared);expect(value.errors).toEqual(expect.arrayContaining([expect.objectContaining({field:'graduationDate',message:'Enter a valid calendar date in YYYY-MM-DD format.'})]))})
  it('rejects malformed, negative, and inconsistent borrowing-history inputs without coercion',()=>{const {plan,shared}=ready();shared.history.directOutstanding=-1;shared.history.lifetimeDirectAndFfel=Number.NaN;shared.history.currentYearDirect[0]=0;shared.history.currentYearSubsidized[0]=1;const value=result(plan,shared);expect(value.errors.map(error=>error.field)).toEqual(expect.arrayContaining(['direct-aggregate-countable-outstanding-principal','lifetime-direct-and-ffel-borrowing','current-year-subsidized-usage']))})
  it('keeps every aggregate family complete, partial with a known subtotal, or incomplete without a subtotal',()=>{const {plan,shared}=ready();const complete=result(plan,shared);for(const metric of Object.values(complete.metrics))expect(metric.status).toBe('complete');plan.subsidizedGross[0]=6_000;const partial=result(plan,shared);for(const key of ['studentGross','studentNet','parentPlusGross','parentPlusNet','fees','gap','surplus','studentPrincipal','studentInterest','studentDebt','parentPrincipal','parentInterest','parentDebt'] as const){expect(['partial','incomplete']).toContain(partial.metrics[key].status);if(partial.metrics[key].status==='partial')expect(partial.metrics[key].knownCents).toBeDefined()}shared.graduationDate='';const incomplete=result(plan,shared);for(const key of ['studentPrincipal','studentInterest','studentDebt','parentPrincipal','parentInterest','parentDebt'] as const){expect(incomplete.metrics[key].status).toBe('incomplete');expect(incomplete.metrics[key].knownCents).toBeUndefined()}})
})
