import AxeBuilder from '@axe-core/playwright'
import { expect,test,type Page } from '@playwright/test'

async function seed(page:Page,names=['Ohio State University-Main Campus']){
  await page.goto('/profile');await page.getByRole('button',{name:'Load fictional demo'}).click();await page.getByRole('button',{name:'Save profile'}).click();await expect(page.getByRole('status')).toContainText('Profile saved locally')
  await page.goto('/app/schools');for(const name of names){await page.getByLabel('Institution name').fill(name);const row=page.getByRole('region',{name:'Find a school'}).getByRole('listitem').filter({has:page.getByText(name,{exact:true})});await row.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('status')).toHaveText(`${name} saved locally.`)}
}
async function openPlanner(page:Page){await page.goto('/app/schools');await page.getByLabel('Institution name').fill('Ohio State University-Main Campus');await page.getByRole('button',{name:'View details'}).click();await page.getByRole('link',{name:'Plan funding for this school'}).click();await expect(page.getByRole('heading',{name:/Build a four- or five-year funding plan/})).toBeVisible()}
async function scope(page:Page){await page.getByLabel('Program identifier').fill('BA-TEST');await page.getByLabel('Program structure').selectOption('supported');await page.getByLabel('Education level').selectOption('undergraduate');await page.getByLabel('Enrollment and academic-year structure').selectOption('full_time_standard_academic_year')}
async function confirmFundingZeros(page:Page,confirmFuturePell=false){await page.getByRole('button',{name:/3\. Grants/}).click();if(confirmFuturePell)for(let year=2;year<=4;year++){await page.getByRole('button',{name:`Year ${year}`,exact:true}).click();await page.getByRole('group',{name:`Pell for Year ${year}`}).getByLabel('Knowledge status').selectOption('known')}for(const label of ['Institutional grant','Outside scholarship','Other grant'])await page.getByRole('group',{name:label}).getByLabel('Knowledge status').selectOption('known');await page.getByRole('button',{name:/4\. Family/}).click();await page.getByRole('group',{name:'Family cash'}).getByLabel('Knowledge status').selectOption('known')}
async function fillHistory(page:Page){await page.getByRole('button',{name:/5\. Student/}).click();await page.locator('#historyStatus').selectOption('confirmed_complete');for(const id of ['direct-aggregate-countable-outstanding-principal','subsidized-aggregate-countable-outstanding-principal','lifetime-direct-and-ffel-borrowing','lifetime-graduate-plus-student-borrowing','parent-plus-borrowed-as-parent-excluded','heal-excluded-borrowing','converted-teach-grant-borrowing','parent-plus-cumulative-usage-for-student'])await page.locator(`#${id}`).fill('0');await page.locator('#consolidation').selectOption('true')}
async function fillYearScope(page:Page,year:number){await page.getByRole('button',{name:`Year ${year}`,exact:true}).click();for(const id of ['current-year-direct-usage','current-year-subsidized-usage','current-year-parent-plus-usage'])await page.locator(`#${id}`).fill('0');await page.locator(`#grade-${year-1}`).selectOption(String(Math.min(year,4)));await page.locator(`#academicYearStart-${year-1}`).fill(`${2025+year}-07-01`);await page.locator(`#enrollmentPeriodStart-${year-1}`).fill(`${2025+year}-07-01`);await page.locator(`#higherLimit-${year-1}`).selectOption('not_qualified')}
async function fillTransitionPredicates(page:Page,applicable=false){for(const [id,value] of [['transition-enrolled',applicable?'yes':'no'],['transition-prior-disbursement',applicable?'yes':'no'],['transition-recipient','student'],['transition-canceled','no'],['transition-remains',applicable?'yes':'no'],['transition-withdrew','no'],['transition-leave','no'],['transition-returned','no'],['transition-expected-time',applicable?'yes':'no']] as const)await page.locator(`#${id}`).selectOption(value)}
async function fillTransitions(page:Page,status='verified_not_applicable'){await page.getByRole('button',{name:/6\. Parent/}).click();await page.getByLabel('Institutional loan-restriction state').selectOption('none_confirmed');for(let year=1;year<=4;year++){await page.getByRole('button',{name:`Year ${year}`,exact:true}).click();await page.getByLabel('Transition-exception determination').selectOption(status);await fillTransitionPredicates(page,status==='verified_applicable')}}
async function fillDates(page:Page){await page.getByRole('button',{name:/7\. Dates/}).click();for(let year=1;year<=4;year++){await page.getByRole('button',{name:`Year ${year}`,exact:true}).click();await page.getByLabel('First disbursement date').fill(`${2025+year}-08-15`)}await page.locator('#disbursementAssumption').check();await page.getByLabel('Graduation or planning-end date').fill('2030-05-15');await page.getByLabel('Subsidized-loan enrollment treatment').selectOption('qualifying_in_school');await page.locator('#inSchoolPayments').check()}

test('unknown defaults, explicit profile scope, privacy, and accessibility',async({page})=>{const traffic:string[]=[],logs:string[]=[];page.on('request',r=>traffic.push(`${r.method()} ${r.url()} ${r.postData()??''}`));page.on('console',m=>logs.push(m.text()));await seed(page);await openPlanner(page);await expect(page.getByText('Dependent-student profile loaded.')).toBeVisible();await expect(page.getByLabel('Program identifier')).toHaveValue('');await scope(page);await page.getByRole('button',{name:/2\. Cost/}).click();await page.getByLabel('Components').click();await expect(page.getByRole('group',{name:'Housing and food'})).toContainText('Unknown');await page.getByRole('button',{name:/3\. Grants/}).click();await expect(page.getByRole('group',{name:'Institutional grant'})).toContainText('Unknown');await page.getByRole('button',{name:/7\. Dates/}).click();await expect(page.getByLabel('First disbursement date')).toHaveValue('');expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);for(const value of ['65000','10000']){expect(traffic.join(' ')).not.toContain(value);expect(logs.join(' ')).not.toContain(value)}})

test('known program cost survives unknown future Pell and print lists detailed missing reasons',async({page})=>{await seed(page);await openPlanner(page);await scope(page);await confirmFundingZeros(page);await page.getByRole('button',{name:/10\. Compare/}).click();await expect(page.getByText('Projected program cost').locator('..')).toContainText('Status: complete');await expect(page.getByText('Grants and scholarships').locator('..')).toContainText('Known partial total');await expect(page.getByText('Specific incomplete items')).toBeVisible();await expect(page.getByText('Future Pell for Year 2: Future Pell unknown for Year 2.',{exact:true})).toBeVisible();await expect(page.getByText(/Detailed household financial-profile values are excluded/)).toBeVisible();await page.evaluate(()=>Object.defineProperty(window,'print',{value:()=>undefined,configurable:true}));await page.getByRole('button',{name:'Print funding summary'}).click()})

test('nonzero history, failed Year 1 election, and verified applicable transition remain explicit',async({page})=>{test.slow();await seed(page);await openPlanner(page);await scope(page);await confirmFundingZeros(page,true);await fillHistory(page);for(let year=1;year<=4;year++)await fillYearScope(page,year);await page.getByRole('button',{name:'Year 1',exact:true}).click();await page.locator('#direct-aggregate-countable-outstanding-principal').fill('25000');await page.getByLabel('Requested Direct Subsidized gross principal').fill('5501');await page.getByRole('button',{name:'Year 2',exact:true}).click();await page.getByLabel('Requested Direct Unsubsidized gross principal').fill('6000');await fillTransitions(page);await page.getByRole('button',{name:'Year 1',exact:true}).click();await page.getByLabel('Transition-exception determination').selectOption('verified_applicable');await fillTransitionPredicates(page,true);await expect(page.getByText(/Evidence: UNITID .* BA-TEST .* 2026-07-01/)).toBeVisible();await fillDates(page);await page.getByRole('button',{name:/8\. Funding/}).click();await expect(page.getByText(/Binding reason:/).first().locator('..')).toContainText(/exceeds/i);await expect(page.getByText('Requested').first().locator('..')).toContainText('$5,501');await expect(page.getByText('Applied').first().locator('..')).toContainText('$0');await expect(page.locator('details').nth(1).getByText('Student gross borrowing').locator('..')).toContainText('$6,000')})

test('known institutional total requires explicit requested, allowed, and applied allocation',async({page})=>{test.slow();await seed(page);await openPlanner(page);await scope(page);await confirmFundingZeros(page,true);await fillHistory(page);for(let year=1;year<=4;year++)await fillYearScope(page,year);await fillTransitions(page);await page.getByLabel('Institutional loan-restriction state').selectOption('known_total_limit');await page.getByLabel('Institutional total').fill('5000');await page.getByLabel('Allocated Subsidized').fill('3000');await page.getByLabel('Allocated Unsubsidized').fill('2000');await page.getByLabel('Allocated Parent PLUS').fill('0');await fillDates(page);await page.getByRole('button',{name:/8\. Funding/}).click();const failure=page.getByText(/Binding reason:/).first().locator('..');await expect(failure).toContainText(/institutional/i);await expect(failure).toContainText('Requested');await expect(failure).toContainText('Allowed');await expect(failure).toContainText('Applied');await expect(failure).toContainText('$5,000');await expect(failure).toContainText('$0')})

test('invalid editable values produce focused accessible errors instead of a crash',async({page})=>{await seed(page);await openPlanner(page);await scope(page);await page.getByRole('button',{name:/2\. Cost/}).click();await page.getByLabel('Percentage').click();await page.getByLabel('Annual growth percent').fill('101');await page.getByLabel('Knowledge status').selectOption('assumed');await page.getByLabel('Assumption explanation').fill('');await expect(page.getByLabel('Annual growth percent')).toHaveAttribute('aria-invalid','true');await expect(page.getByLabel('Assumption explanation')).toHaveAttribute('aria-invalid','true');await page.getByRole('button',{name:/8\. Funding/}).click();const alert=page.getByRole('alert');await expect(alert).toBeFocused();await expect(alert).toContainText('growth percentage');await expect(alert).toContainText('Explain this planning assumption');const recovery=alert.getByRole('button',{name:/growth percentage/i});await recovery.focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:/Step 2: Cost assumptions/})).toBeVisible();await expect(page.getByLabel('Annual growth percent')).toBeFocused()})

test('third school selection is explained and reload clears only ephemeral planner state',async({page})=>{await seed(page,['Ohio State University-Main Campus','Howard University','Stanford University']);await page.goto('/app/funding-planner');await page.getByLabel('Ohio State University-Main Campus (OH)').check();await page.getByLabel('Howard University (DC)').check();await page.getByLabel('Stanford University (CA)').click();await expect(page.getByRole('status')).toContainText('exactly two schools');await expect(page.getByLabel('Stanford University (CA)')).not.toBeChecked();await page.getByLabel('5 years').check();await scope(page);await page.reload();await expect(page.getByLabel('4 years')).toBeChecked();await expect(page.getByLabel('Ohio State University-Main Campus (OH)')).not.toBeChecked();await page.goto('/app/schools');await expect(page.getByRole('heading',{name:/Saved schools \(3\/10\)/})).toBeVisible()})
