import AxeBuilder from '@axe-core/playwright'
import { expect,test,type Page } from '@playwright/test'

const noHorizontalOverflow=async(page:Page)=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
const choose=async(page:Page,label:string,value:string)=>page.locator('label').filter({hasText:label}).locator('select').first().selectOption(value)

async function completeIncomeStep(page:Page,agi:string,tax:string,work:string,filing:string){
  const inputs=page.locator('input[type="number"]')
  for(let index=0;index<await inputs.count();index++)await inputs.nth(index).fill('0')
  await page.getByLabel('Adjusted gross income (AGI)',{exact:true}).fill(agi)
  await page.getByLabel('Income tax paid',{exact:true}).fill(tax)
  await page.getByLabel('Income earned from work',{exact:true}).fill(work)
  await choose(page,'Tax filing status',filing)
}

async function completeRiveraGuidedProfile(page:Page){
  await page.getByLabel('Student name').fill('Maya Rivera')
  await page.getByLabel('Household label').fill('Rivera household')
  await choose(page,'State or location','OH')
  await page.getByRole('spinbutton',{name:'Family size',exact:true}).fill('4')
  await page.getByRole('button',{name:/Next: Parent\/contributor/}).click()
  await choose(page,'Parents’ living arrangement','married_together')
  await expect(page.getByText('Include information for both parents.')).toBeVisible()
  await page.getByRole('button',{name:/Next: Parent income/}).click()
  await completeIncomeStep(page,'65000','4000','65000','married_filing_jointly')
  await page.getByRole('button',{name:/Next: Parent tax/}).click()
  await page.getByLabel('Pell cost of attendance').fill('9000')
  await choose(page,'Parent is a qualifying nonfiler','false')
  await choose(page,'Possible statutory special-rule dependent','false')
  await choose(page,'Filed Schedule A, B, D, E, F, or H','true')
  await choose(page,'Parents live outside the U.S.','false')
  await choose(page,'Parents filed a U.S. or territory return','true')
  await choose(page,'Nonfiling because income was below the filing threshold','false')
  await choose(page,'Schedule C','not_filed')
  await choose(page,'Means-tested benefit list is complete, including none','true')
  await page.getByRole('button',{name:/Next: Parent assets/}).click()
  await page.getByRole('button',{name:'Enter parent assets'}).click()
  await page.getByLabel('Annual child support received').fill('0')
  await page.getByLabel('Cash, savings, and checking').fill('10000')
  await page.getByLabel('Investment net worth').fill('2000')
  await choose(page,'Business/farm list is complete, including none','true')
  await page.getByRole('button',{name:/Next: Student income/}).click()
  await completeIncomeStep(page,'5000','0','5000','dependent_student')
  await page.getByRole('button',{name:/Next: Student assets/}).click()
  await page.getByRole('button',{name:'Enter student assets'}).click()
  await page.getByLabel('Cash, savings, and checking').fill('2000')
  await page.getByLabel('Investment net worth').fill('0')
  await choose(page,'Business/farm list is complete, including none','true')
  await page.getByRole('button',{name:/Next: Review/}).click()
  await expect(page.getByText('Complete',{exact:true})).toBeVisible()
}

test('journey A: guided household, contributor result, aid traces, and private print summary',async({page})=>{
  test.slow()
  const requests:string[]=[],logs:string[]=[]
  page.on('request',request=>requests.push(`${request.method()} ${request.url()} ${request.postData()??''}`))
  page.on('console',message=>logs.push(message.text()))
  await page.goto('/')
  await page.getByRole('link',{name:'Start with my information'}).click()
  await completeRiveraGuidedProfile(page)
  const undersizedTargets=await page.getByRole('button').evaluateAll(buttons=>buttons.filter(button=>button.getClientRects().length>0&&button.getBoundingClientRect().height<40).map(button=>({name:button.textContent?.trim(),height:button.getBoundingClientRect().height})))
  expect(undersizedTargets).toEqual([])
  await noHorizontalOverflow(page)
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
  await page.getByRole('button',{name:'Save profile and estimate federal aid'}).click()
  await expect(page.getByTestId('calculated-sai')).toHaveText('2,069')
  await expect(page.getByTestId('pell-award')).toHaveText('$5,325')
  await page.getByText('Show how we calculated your SAI').click()
  await expect(page.getByTestId('sai-trace')).toContainText('Final bounded SAI')
  await page.getByRole('link',{name:'Print family summary'}).click()
  await expect(page.getByRole('heading',{name:'Printable planning summary'})).toBeVisible()
  await noHorizontalOverflow(page)
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
  await page.evaluate(()=>{Object.defineProperty(window,'print',{value:()=>undefined,configurable:true})})
  await page.getByRole('button',{name:'Print summary'}).click()
  for(const sentinel of ['65000','10000','5000','2000']){expect(requests.join(' ')).not.toContain(sentinel);expect(logs.join(' ')).not.toContain(sentinel)}
  expect(requests.every(value=>value.startsWith('GET http://127.0.0.1:4173/'))).toBe(true)
})

test('journey B: fictional demo what-if is discarded without mutating the baseline',async({page})=>{
  await page.goto('/')
  await page.getByRole('link',{name:'Explore with fictional demo'}).click()
  await expect(page.getByText('Complete',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Save profile and estimate federal aid'}).click()
  await expect(page.getByTestId('calculated-sai')).toHaveText('2,069')
  await page.getByRole('button',{name:'Start a what-if scenario'}).click()
  await page.getByLabel('Scenario parent AGI').fill('55000')
  await expect(page.getByTestId('scenario-sai')).not.toHaveText('2,069')
  await expect(page.getByText('Current profile compared with unsaved scenario')).toBeVisible()
  await noHorizontalOverflow(page)
  await page.getByRole('button',{name:'Exit without saving'}).click()
  await page.reload()
  await expect(page.getByTestId('calculated-sai')).toHaveText('2,069')
  await expect(page.getByTestId('pell-award')).toHaveText('$5,325')
})

test('journey C: existing borrower sees Tiered Standard extra-payment payoff comparison',async({page})=>{
  await page.goto('/')
  await page.getByRole('link',{name:'I already have federal student loans'}).click()
  await choose(page,'Extra-payment pattern','recurring')
  await page.getByLabel('Extra amount').fill('50')
  await page.getByRole('button',{name:'Save loan scenario'}).click()
  const card=page.getByTestId('loan-scenario')
  await expect(card.getByText('Extra-payment effects are shown only for Tiered Standard.')).toBeVisible()
  const tiered=card.getByRole('heading',{name:'Tiered Standard'}).locator('..')
  await expect(tiered).toContainText('Effect versus no extra payment')
  await expect(tiered).toContainText('fewer projected months')
  await expect(card).toContainText('RAP and IBR projections below use no extra payment')
  await noHorizontalOverflow(page)
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
})
