import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { Link } from 'react-router-dom'
import { PageShell } from '../components/PageShell'
import { useProductionSnapshot } from '../lib/scorecard/production'
import { formatDebtToEarnings,formatScorecardMoney,formatScorecardPercent,getComparableSchoolValues,INCOME_BRACKETS,resolveSavedSchools,selectFieldOfStudyEarnings,sortSchools,type ComparisonSort,type IncomeBracket } from '../lib/scorecard/comparison'
import type { SchoolRecord } from '../lib/scorecard/schema'
import { savedSchoolRepository } from '../lib/storage/repositories'

const bracketLabel:Record<IncomeBracket,string>={'0-30000':'$0–$30,000','30001-48000':'$30,001–$48,000','48001-75000':'$48,001–$75,000','75001-110000':'$75,001–$110,000','110001-plus':'$110,001+'}
export function ComparePage(){const snapshot=useProductionSnapshot();return snapshot?<CompareLoaded scorecardSnapshot={snapshot}/>:<PageShell eyebrow="Compare" title="Loading school data…" intro="Loading the same-origin static national snapshot."/ >}
function CompareLoaded({scorecardSnapshot}:{scorecardSnapshot:NonNullable<ReturnType<typeof useProductionSnapshot>>}){
  const saved=useLiveQuery(()=>savedSchoolRepository.list(),[],[]),[sort,setSort]=useState<ComparisonSort>('saved_order'),[bracket,setBracket]=useState<IncomeBracket>('48001-75000'),[intendedCip,setIntendedCip]=useState(''),[notice,setNotice]=useState('')
  const schools=resolveSavedSchools(saved,scorecardSnapshot.records)
  const displayed=sortSchools(schools,sort,bracket,intendedCip||undefined),fieldOptions=[...new Map(schools.flatMap((school)=>school.fieldOfStudyEarnings).map((field)=>[field.cipCode,field])).values()]
  const remove=async(school:SchoolRecord)=>{await savedSchoolRepository.remove(school.unitId);setNotice(`${school.name} removed from saved schools and this comparison.`)}
  return <PageShell eyebrow="Compare" title="Compare saved schools, one metric at a time." intro="Use neutral College Scorecard outcomes to inspect tradeoffs. No overall score or personalized institutional-aid estimate is created.">
    {schools.length<2?<section className="card max-w-3xl p-6 sm:p-8"><h2 className="font-serif text-2xl font-bold">{schools.length===0?'Save schools to begin':'Add one more school'}</h2><p className="mt-3 text-ink-700">{schools.length===0?'No schools are currently saved on this device.':'A side-by-side comparison needs at least two saved schools.'}</p>{schools.length===1?<p className="mt-3 font-bold">Currently saved: {schools[0].name}</p>:null}<Link className="button-primary mt-5" to="/app/schools">Find and save schools</Link></section>:<>
      <section className="card p-5" aria-labelledby="compare-controls-heading"><h2 id="compare-controls-heading" className="font-serif text-2xl font-bold">Comparison controls</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm font-bold">Sort saved schools by<select value={sort} onChange={(event)=>setSort(event.target.value as ComparisonSort)} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="saved_order">Saved order</option><option value="cost_low">Lowest published cost</option><option value="net_price_low">Lowest average net price</option><option value="graduation_high">Highest graduation rate</option><option value="debt_low">Lowest Scorecard median federal debt</option><option value="earnings_high">Highest available earnings</option><option value="debt_to_earnings_low">Lowest debt-to-first-year-earnings ratio</option></select></label><label className="grid gap-2 text-sm font-bold">Federal income bracket<select value={bracket} onChange={(event)=>setBracket(event.target.value as IncomeBracket)} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal">{INCOME_BRACKETS.map((value)=><option key={value} value={value}>{bracketLabel[value]}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Intended field of study<select value={intendedCip} disabled={fieldOptions.length===0} onChange={(event)=>setIntendedCip(event.target.value)} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal disabled:bg-gray-100"><option value="">{fieldOptions.length?'Institution-level earnings':'No field data available'}</option>{fieldOptions.map((field)=><option key={field.cipCode} value={field.cipCode}>{field.title??`CIP ${field.cipCode}`}</option>)}</select></label></div><p className="mt-3 text-sm text-ink-700">Sorting uses only the selected metric, leaves missing values last, and does not name an overall winner.</p></section>
      <p role="status" className="mt-4 min-h-6 text-sm font-bold text-moss-700">{notice}</p>
      <section className="mt-2 overflow-x-auto pb-4" aria-label="Saved school comparison"><div className="grid auto-cols-[minmax(18rem,1fr)] grid-flow-col gap-4">{displayed.map((school)=><ComparisonCard key={school.unitId} school={school} bracket={bracket} intendedCip={intendedCip} remove={()=>remove(school)}/>)}</div></section>
      <div className="mt-4 rounded-lg border border-line bg-gold-100 p-5 text-sm"><p><strong>How to read this:</strong> published cost is the sticker cost. Average net prices are historical College Scorecard averages, not your guaranteed price or financial-aid offer. Institutional aid varies substantially; each school provides the actual offer.</p><p className="mt-2">The debt-to-first-year-earnings ratio is a neutral comparison heuristic using Scorecard median federal debt divided by a valid Scorecard median annual earnings value one year after entry. It is not an investment pass/fail judgment or your projected debt.</p></div>
    </>}
    <Link className="mt-5 inline-block text-moss-700 underline" to="/methodology#comparison">How is this comparison calculated?</Link>
  </PageShell>
}

function ComparisonCard({school,bracket,intendedCip,remove}:{school:SchoolRecord;bracket:IncomeBracket;intendedCip:string;remove:()=>void}){
  const values=getComparableSchoolValues(school,bracket,intendedCip||undefined),field=selectFieldOfStudyEarnings(school,intendedCip||undefined)
  return <article className="card flex min-w-0 flex-col p-5" data-testid={`comparison-school-${school.unitId}`}><div className="min-h-28"><p className="eyebrow">{school.state} · UNITID {school.unitId}</p><h2 className="mt-2 font-serif text-2xl font-bold">{school.name}</h2></div><dl className="mt-5 grid gap-3"><Row label="Published cost of attendance" value={formatScorecardMoney(values.publishedCost)}/><Row label="College Scorecard average net price" value={formatScorecardMoney(values.averageNetPrice)}/><Row label={`Average net price · ${bracketLabel[bracket]}`} value={formatScorecardMoney(values.incomeBracketNetPrice)}/><Row label="Graduation rate" value={formatScorecardPercent(values.graduationRate)}/><Row label="Scorecard median federal debt" value={formatScorecardMoney(values.medianFederalDebt)}/><Row label="Median earnings · 1 year after entry" value={formatScorecardMoney(values.earningsOneYear)}/><Row label="Median earnings · 4 years after entry" value={formatScorecardMoney(values.earningsFourYears)}/><Row label="Median earnings · 10 years after entry" value={formatScorecardMoney(values.earningsTenYears)}/><Row label="Field-of-study earnings" value={field.source==='field_of_study'?formatScorecardMoney(field.value):'Not available'} note={field.source==='institution'?'Institution-level earnings are shown separately; no matching field record is available.':undefined}/><Row label="Debt-to-first-year-earnings ratio" value={formatDebtToEarnings(values.debtToFirstYearEarnings)}/></dl><button type="button" className="button-secondary mt-5" onClick={remove}>Remove from comparison</button></article>
}
function Row({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-lg bg-moss-100 p-3"><dt className="text-xs font-bold uppercase tracking-wide text-ink-700">{label}</dt><dd className="mt-1 text-lg font-bold">{value}</dd>{note?<dd className="mt-1 text-xs text-ink-700">{note}</dd>:null}</div>}
