import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { describe,expect,it,vi } from 'vitest'
import { FundingPlannerPage } from './FundingPlannerPage'

const school=(unitId:number,name:string)=>({unitId,name,state:'OH',control:'public' as const,costOfAttendance:30_000+unitId,tuitionInState:12_000,tuitionOutOfState:25_000,averageNetPrice:18_000,averageNetPriceByIncome:{'0-30000':null,'30001-48000':null,'48001-75000':null,'75001-110000':null,'110001-plus':null},graduationRate:.7,medianFederalDebtAtGraduation:20_000,earnings:[],fieldOfStudyEarnings:[],dataYear:'2023'})
const schools=[school(1,'Test University'),school(2,'Second College'),school(3,'Third Institute')]
vi.mock('../lib/scorecard/production',()=>({useProductionSnapshot:()=>({metadata:{recordCount:3,scorecardDataYear:'2023',snapshotVersion:'test'},records:schools})}))
vi.mock('../lib/storage/repositories',()=>({savedSchoolRepository:{list:()=>schools.map(s=>({unitId:s.unitId,snapshotVersion:'test',addedAt:'2026-01-01'}))},householdRepository:{load:()=>undefined}}))
vi.mock('dexie-react-hooks',()=>({useLiveQuery:(callback:()=>unknown)=>callback()}))
const renderPage=(ids=[1])=>render(<MemoryRouter initialEntries={[{pathname:'/app/funding-planner',state:{fundingSchoolIds:ids}}]}><FundingPlannerPage/></MemoryRouter>)

describe('ephemeral funding planner UI',()=>{
  it('starts optional components and funding facts unknown and dates unconfirmed',async()=>{const user=userEvent.setup();renderPage();await user.click(screen.getByRole('button',{name:/2\. Cost/}));await user.click(screen.getByLabelText('Components'));expect(screen.getAllByText('Unknown is not converted to $0.').length).toBeGreaterThanOrEqual(4);expect(screen.getByRole('group',{name:'Housing and food'})).toHaveTextContent('Unknown');await user.click(screen.getByRole('button',{name:/3\. Grants/}));expect(screen.getByRole('group',{name:'Institutional grant'})).toHaveTextContent('Unknown');await user.click(screen.getByRole('button',{name:/7\. Dates/}));expect(document.getElementById('disbursementDate-0')).toHaveValue('');expect(document.getElementById('graduationDate')).toHaveValue('')})
  it('does not crash when Year 5 custom aid becomes out of range after a four-year switch',async()=>{const user=userEvent.setup();renderPage();await user.click(screen.getByLabelText('5 years'));await user.click(screen.getByRole('button',{name:/3\. Grants/}));await user.selectOptions(screen.getByLabelText('Schedule',{selector:'#grant-schedule'}),'custom_year');const customYear=document.getElementById('funding-grant-year')!;await user.clear(customYear);await user.type(customYear,'5');await user.click(screen.getByRole('button',{name:/1\. School/}));await user.click(screen.getByLabelText('4 years'));await user.click(screen.getByRole('button',{name:/8\. Funding/}));expect(screen.getByRole('alert')).toHaveTextContent(/custom year within this 4-year plan/i)})
  it('shows an accessible error summary for an empty assumption explanation instead of throwing',async()=>{const user=userEvent.setup();renderPage();await user.click(screen.getByRole('button',{name:/2\. Cost/}));await user.selectOptions(screen.getByLabelText('Knowledge status'),'assumed');expect(document.getElementById('totalCost-explanation')).toHaveAttribute('aria-invalid','true');await user.click(screen.getByRole('button',{name:/8\. Funding/}));const alert=screen.getByRole('alert');expect(alert).toHaveFocus();expect(alert).toHaveTextContent('Explain this planning assumption')})
  it('explains the two-school limit, shares growth, and keeps school costs independent',async()=>{const user=userEvent.setup();renderPage([1,2]);await user.click(screen.getByLabelText('Third Institute (OH)'));expect(screen.getByRole('status')).toHaveTextContent('exactly two schools');await user.click(screen.getByRole('button',{name:/2\. Cost/}));await user.click(screen.getByLabelText('Percentage'));const growth=document.getElementById('growth')!;await user.clear(growth);await user.type(growth,'3');await user.selectOptions(screen.getByLabelText('Knowledge status'),'assumed');const amount=document.getElementById('totalCost-amount')!;await user.clear(amount);await user.type(amount,'41000');await user.click(screen.getByRole('button',{name:/1\. School/}));await user.selectOptions(screen.getByLabelText('School-specific inputs'),'2');await user.click(screen.getByRole('button',{name:/2\. Cost/}));expect(document.getElementById('growth')).toHaveValue(3);expect(document.getElementById('totalCost-amount')).not.toHaveValue(41000)})
  it('prints year-by-year gross, fee, and net fields without private profile details',async()=>{const user=userEvent.setup(),print=vi.spyOn(window,'print').mockImplementation(()=>undefined);renderPage();await user.click(screen.getByRole('button',{name:/10\. Compare/}));expect(screen.getByText(/No winner, rank, score, ROI/)).toBeVisible();expect(screen.getByText(/Detailed household financial-profile values are excluded/)).toBeVisible();expect(screen.getByText('Year-by-year funding')).toBeVisible();expect(document.body).toHaveTextContent('student gross');expect(document.body).toHaveTextContent('fees');expect(document.body).toHaveTextContent('net proceeds');await user.click(screen.getByRole('button',{name:'Print / Save planning summary'}));expect(print).toHaveBeenCalledOnce();expect(document.body).not.toHaveTextContent('65000')})
  it('recovers an unmounted error-summary target by changing step and focusing the field',async()=>{const user=userEvent.setup();renderPage();await user.click(screen.getByRole('button',{name:/8\. Funding/}));expect(screen.getByRole('alert')).toBeVisible();const target=screen.getByRole('button',{name:/Enter the school program identifier/});await user.click(target);await waitFor(()=>expect(screen.getByRole('heading',{name:/Step 1: School/})).toBeVisible());await waitFor(()=>expect(document.getElementById('programIdentifier')).toHaveFocus())})
  it('keeps one what-if scenario ephemeral and restores the unchanged baseline',async()=>{const user=userEvent.setup();renderPage();await user.click(screen.getByRole('button',{name:/10\. Compare/}));await user.click(screen.getByRole('button',{name:'Duplicate current plan as a what-if scenario'}));await user.click(screen.getByRole('button',{name:/2\. Cost/}));const amount=document.getElementById('totalCost-amount')!;expect(amount).toHaveValue(30001);await user.clear(amount);await user.type(amount,'41000');await user.click(screen.getByRole('button',{name:/10\. Compare/}));expect(screen.getByText('Baseline vs What-if scenario')).toBeVisible();await user.click(screen.getByRole('button',{name:'Discard what-if and restore baseline'}));await user.click(screen.getByRole('button',{name:/2\. Cost/}));expect(document.getElementById('totalCost-amount')).toHaveValue(30001)})
})
