import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { Link } from 'react-router-dom'
import { householdRepository } from '../lib/storage/repositories'

export function HomePage() {
  const profile=useLiveQuery(()=>householdRepository.load(),[],null),[dismissed,setDismissed]=useState(false)
  return <>
    <section className="page-wrap grid gap-12 py-16 sm:py-24 lg:grid-cols-[1.15fr_.85fr] lg:items-center">
      <div><p className="eyebrow">A clearer path through college costs</p><h1 className="display mt-5 max-w-3xl">Plan with context, not guesswork.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink-700">Bring college costs, aid assumptions, school choices, and repayment questions into one calm planning space.</p>{profile===undefined&&!dismissed?<section className="card mt-8 p-5" aria-labelledby="first-use-heading"><div className="flex items-start justify-between gap-4"><div><h2 id="first-use-heading" className="font-serif text-2xl font-bold">Where would you like to start?</h2><p className="mt-2 text-sm">Your financial information stays in this browser. No account is required.</p></div><button type="button" className="min-h-11 font-bold text-moss-700 underline" onClick={()=>setDismissed(true)}>Dismiss</button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Link className="button-primary text-center" to="/profile?mode=guided">Start with my information</Link><Link className="button-secondary text-center" to="/profile?mode=guided&demo=1">Explore with fictional demo</Link><Link className="button-secondary text-center" to="/app/repayment">I already have federal student loans</Link></div><p className="mt-3 text-xs text-ink-700">The existing-borrower path opens repayment directly; a household aid profile is not required.</p></section>:<div className="mt-8 flex flex-wrap gap-3"><Link to="/profile" className="button-primary">Open household profile</Link><Link to="/app/repayment" className="button-secondary">I already have federal student loans</Link><Link to="/how-it-works" className="button-secondary">See how it works</Link></div>}<p className="mt-4 text-sm text-ink-500">No sign-in. Profiles stay in this browser; dependent-student aid and Direct Loan estimates run locally.</p></div>
      <aside className="card overflow-hidden" aria-label="Planning preview"><div className="bg-moss-700 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-moss-100">Sample planning view</p><p className="mt-3 font-serif text-3xl">The Rivera household</p><p className="mt-2 text-sm text-moss-100">Fictional data · dependent student</p></div><div className="grid gap-4 p-6"><div className="rounded-lg bg-gold-100 p-4"><p className="text-sm font-bold">Policy-aware by design</p><p className="mt-1 text-sm leading-6 text-ink-700">Estimates use the frozen policy baseline verified August 7, 2026.</p></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg border border-line p-4"><span className="text-ink-500">Schools</span><strong className="mt-2 block text-2xl">—</strong></div><div className="rounded-lg border border-line p-4"><span className="text-ink-500">Aid estimate</span><strong className="mt-2 block text-2xl">Not run</strong></div></div></div></aside>
    </section>
    <section className="border-y border-line bg-white py-14"><div className="page-wrap grid gap-6 md:grid-cols-3">{[['Private by default','Your household profile stays in this browser and can be deleted at any time.'],['Transparent assumptions','Policy years, sources, and unsupported scenarios are shown instead of hidden.'],['Built for comparison','Keep the full cost picture visible as you consider schools and borrowing.']].map(([title, text], index) => <article key={title} className="p-2"><span className="font-serif text-3xl text-gold-500">0{index + 1}</span><h2 className="mt-4 text-lg font-extrabold">{title}</h2><p className="mt-2 leading-7 text-ink-700">{text}</p></article>)}</div></section>
  </>
}
