import { useState,type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { useLiveQuery } from 'dexie-react-hooks'
import { InlineDefinition,NextStepActions } from '../components/Explainability'
import { PageShell } from '../components/PageShell'
import { calculateProfileAid } from '../lib/calculations'
import { searchSchools } from '../lib/scorecard/catalog'
import { useProductionSnapshot } from '../lib/scorecard/production'
import { deriveHouseholdIncomeBracket,formatScorecardMoney,formatScorecardPercent,getComparableSchoolValues,INCOME_BRACKET_LABELS,INCOME_BRACKETS,type IncomeBracket } from '../lib/scorecard/comparison'
import type { SchoolRecord } from '../lib/scorecard/schema'

import { householdRepository,SAVED_SCHOOL_LIMIT,SavedSchoolLimitError,savedSchoolRepository } from '../lib/storage/repositories'

export function SchoolsPage(){const snapshot=useProductionSnapshot();return snapshot?<SchoolsLoaded scorecardSnapshot={snapshot}/>:<PageShell eyebrow="Schools" title="Loading school data…" intro="Loading the same-origin static national snapshot."/ >}
function SchoolsLoaded({scorecardSnapshot}:{scorecardSnapshot:NonNullable<ReturnType<typeof useProductionSnapshot>>}){
  const [query,setQuery]=useState(''),[state,setState]=useState(''),[selectedId,setSelectedId]=useState<number>(),[notice,setNotice]=useState('')
  const saved=useLiveQuery(()=>savedSchoolRepository.list(),[],[]),profile=useLiveQuery(()=>householdRepository.load())
  const results=searchSchools(scorecardSnapshot.records,query,state),selected=scorecardSnapshot.records.find((school)=>school.unitId===selectedId)
  const savedIds=new Set(saved.map((school)=>school.unitId)),aid=profile?calculateProfileAid(profile):undefined
  const toggleSaved=async(school:SchoolRecord)=>{try{if(savedIds.has(school.unitId)){await savedSchoolRepository.remove(school.unitId);setNotice(`${school.name} removed.`)}else{await savedSchoolRepository.save(school.unitId,scorecardSnapshot.metadata.snapshotVersion);setNotice(`${school.name} saved locally.`)}}catch(error){setNotice(error instanceof SavedSchoolLimitError?error.message:'Unable to update saved schools.')}}
  return <PageShell eyebrow="Schools" title="Explore published school costs and outcomes." intro="Search the national institution-level College Scorecard snapshot. School data is bundled with the app; your household information never enters a school-data request.">
    <div className="rounded-lg border border-line bg-gold-100 p-4 text-sm"><strong>National institution snapshot:</strong> {scorecardSnapshot.metadata.recordCount} schools from the {scorecardSnapshot.metadata.scorecardDataYear}. Metrics use different cohorts. Missing values stay unavailable.</div>
    <section className="card mt-6 p-6" aria-labelledby="school-search-heading"><h2 id="school-search-heading" className="font-serif text-2xl font-bold">Find a school</h2><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_12rem]"><label className="grid gap-2 text-sm font-bold">Institution name<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Try Ohio or Technology" className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"/></label><label className="grid gap-2 text-sm font-bold">State<select value={state} onChange={(event)=>setState(event.target.value)} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="">All states</option>{[...new Set(scorecardSnapshot.records.map((school)=>school.state))].sort().map((code)=><option key={code} value={code}>{code}</option>)}</select></label></div>
      <p className="mt-4 text-sm text-ink-700">{results.length} result{results.length===1?'':'s'}{results.length>50?' — showing the first 50; narrow your name or state search.':''}</p>{results.length===0?<p className="mt-4 rounded-lg bg-moss-100 p-4">No schools match that name and state.</p>:<ul className="mt-3 grid gap-3">{results.slice(0,50).map((school)=><li key={school.unitId} className="flex flex-wrap items-center justify-between gap-4 rounded-lg border border-line p-4"><div><p className="font-bold">{school.name}</p><p className="text-sm text-ink-700">{school.state} · {school.control.replaceAll('_',' ')} · UNITID {school.unitId}</p></div><div className="flex gap-2"><button className="button-secondary" type="button" onClick={()=>setSelectedId(school.unitId)}>View details</button><button className="button-primary" type="button" onClick={()=>toggleSaved(school)}>{savedIds.has(school.unitId)?'Remove':'Save'}</button></div></li>)}</ul>}</section>
    <p className="mt-4 min-h-6 text-sm font-bold text-moss-700" role="status">{notice}</p>
    <Link className="text-moss-700 underline" to="/methodology#scorecard">How are school costs and outcomes reported?</Link>
    {selected?<SchoolDetails school={selected} aid={aid} suggestedBracket={deriveHouseholdIncomeBracket(profile)}/>:null}
    <section className="card mt-6 p-6"><h2 className="font-serif text-2xl font-bold">Saved schools <span className="text-base font-normal">({saved.length}/{SAVED_SCHOOL_LIMIT})</span></h2>{saved.length===0?<p className="mt-3 text-ink-700">No schools saved on this device.</p>:<ul className="mt-4 grid gap-3">{saved.map((entry)=>{const school=scorecardSnapshot.records.find((item)=>item.unitId===entry.unitId);return school?<li key={entry.unitId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-moss-100 p-4"><button type="button" className="font-bold text-moss-700 underline" onClick={()=>setSelectedId(school.unitId)}>{school.name}</button><button type="button" className="button-secondary" onClick={()=>toggleSaved(school)}>Remove</button></li>:<li key={entry.unitId}>School unavailable in snapshot {entry.snapshotVersion}.</li>})}</ul>}</section>
    <NextStepActions actions={[{to:'/app/compare',label:'Compare saved schools'},{to:'/app/summary',label:'Print family summary'}]}/>
  </PageShell>
}

function SchoolDetails({school,aid,suggestedBracket}:{school:SchoolRecord;aid:ReturnType<typeof calculateProfileAid>|undefined;suggestedBracket:IncomeBracket|null}){
  const [manualBracket,setManualBracket]=useState<IncomeBracket|''>(''),bracket=manualBracket||suggestedBracket||''
  const values=getComparableSchoolValues(school,bracket||undefined)
  return <section className="card mt-6 p-6 sm:p-8" aria-labelledby="school-detail-heading"><p className="eyebrow">School details</p><h2 id="school-detail-heading" className="mt-2 font-serif text-3xl font-bold">{school.name}</h2><p className="mt-2 text-sm text-ink-700">College Scorecard UNITID {school.unitId} · {school.dataYear}</p>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Metric label={<InlineDefinition term="Published cost" learnMore="/methodology#scorecard">The school’s listed cost before grants and scholarships.</InlineDefinition>} value={formatScorecardMoney(values.publishedCost)}/><Metric label="Tuition and fees — in state" value={formatScorecardMoney(school.tuitionInState)}/><Metric label="Tuition and fees — out of state" value={formatScorecardMoney(school.tuitionOutOfState)}/><Metric label={<InlineDefinition term="College Scorecard average net price" learnMore="/methodology#scorecard">A historical average cost after grants and scholarships for the reported student cohort.</InlineDefinition>} value={formatScorecardMoney(values.averageNetPrice)}/><Metric label="Graduation rate" value={formatScorecardPercent(values.graduationRate)}/><Metric label={<InlineDefinition term="Federal student debt" learnMore="/methodology#scorecard">The Scorecard median federal debt measure; it is not a personal borrowing forecast.</InlineDefinition>} value={formatScorecardMoney(values.medianFederalDebt)}/></div>
    <section className="mt-7 rounded-lg border border-line p-5" aria-labelledby="bracket-price-heading"><h3 id="bracket-price-heading" className="font-serif text-xl font-bold">Income-bracket net price</h3><div className="mt-2 text-sm"><InlineDefinition term="Income-bracket net price" learnMore="/methodology#scorecard">A historical College Scorecard average for Title IV students in one reported family-income range.</InlineDefinition></div><p className="mt-2 text-sm">College Scorecard reports historical averages by family income. For dependent students, the local suggestion uses parent AGI plus student AGI. No household value leaves this browser.</p><label className="mt-4 grid max-w-md gap-2 text-sm font-bold">Selected family income bracket<select value={bracket} onChange={event=>setManualBracket(event.target.value as IncomeBracket| '')} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="">Choose a bracket</option>{INCOME_BRACKETS.map(value=><option key={value} value={value}>{INCOME_BRACKET_LABELS[value]}</option>)}</select></label>{suggestedBracket&&!manualBracket?<p className="mt-2 text-sm font-bold text-moss-700">Suggested locally from the complete household profile: {INCOME_BRACKET_LABELS[suggestedBracket]}</p>:null}<div className="mt-4 rounded-lg bg-moss-100 p-4"><p className="text-sm text-ink-700">Average net price for households in your selected income bracket</p><p className="mt-1 text-2xl font-bold" data-testid="selected-bracket-price">{bracket?formatScorecardMoney(values.incomeBracketNetPrice):'Select a bracket'}</p></div><p className="mt-3 text-sm">Students in the same income range can still receive very different aid packages. This is a historical average, not your personal net price.</p></section>
    <h3 className="mt-7 font-serif text-xl font-bold">All published income brackets</h3><dl className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(school.averageNetPriceByIncome).map(([value,price])=><div key={value} className={`flex justify-between gap-4 rounded-lg px-4 py-3 ${value===bracket?'border-2 border-moss-700 bg-moss-100':'bg-moss-100'}`}><dt>{INCOME_BRACKET_LABELS[value as IncomeBracket]}</dt><dd className="font-bold">{formatScorecardMoney(price)}</dd></div>)}</dl>
    <h3 className="mt-7 font-serif text-xl font-bold">Earnings outcomes</h3>{school.earnings.length?<dl className="mt-3 grid gap-3">{school.earnings.map(outcome=><div key={outcome.label} className="rounded-lg bg-moss-100 p-4"><dt>{outcome.label}</dt><dd className="mt-1 font-bold">{formatScorecardMoney(outcome.value)}</dd></div>)}</dl>:<p className="mt-3">Not available.</p>}
    <div className="mt-7 rounded-lg border border-line p-5"><h3 className="font-serif text-xl font-bold">Your federal estimate stays separate</h3>{aid?.status==='calculated'?<p className="mt-3">Your locally calculated SAI is <strong>{aid.sai.sai.toLocaleString()}</strong>{aid.pell.status==='eligible'?<> and your Pell Scheduled Award estimate is <strong>{formatScorecardMoney(aid.pell.scheduledAward)}</strong></>:null}. These values are not subtracted here to claim an exact school net price.</p>:<p className="mt-3">Complete a supported dependent-student household profile to see the separate federal SAI/Pell estimate.</p>}<p className="mt-3 text-sm">This federal estimate does not include state grants, institutional grants, private scholarships, or other school-specific aid. The school provides the actual offer.</p><Link className="button-primary mt-4" to="/app/funding-planner" state={{fundingSchoolIds:[school.unitId]}}>Plan funding for this school</Link></div>
  </section>
}
function Metric({label,value}:{label:ReactNode;value:string}){return <div className="rounded-lg bg-moss-100 p-4"><div className="text-sm text-ink-700">{label}</div><p className="mt-1 text-lg font-bold">{value}</p></div>}
