import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { PageShell } from '../components/PageShell'
import { calculateProfileAid } from '../lib/calculations'
import { scorecardSnapshot,searchSchools } from '../lib/scorecard/catalog'
import { formatScorecardMoney,formatScorecardPercent,getComparableSchoolValues } from '../lib/scorecard/comparison'
import type { SchoolRecord } from '../lib/scorecard/schema'
import { navigatorDatabase } from '../lib/storage/database'
import { SAVED_SCHOOL_LIMIT,SavedSchoolLimitError,savedSchoolRepository } from '../lib/storage/repositories'

export function SchoolsPage(){
  const [query,setQuery]=useState(''),[state,setState]=useState(''),[selectedId,setSelectedId]=useState<number>(),[notice,setNotice]=useState('')
  const saved=useLiveQuery(()=>savedSchoolRepository.list(),[],[]),profile=useLiveQuery(()=>navigatorDatabase.profiles.get('current-household'))
  const results=searchSchools(scorecardSnapshot.records,query,state),selected=scorecardSnapshot.records.find((school)=>school.unitId===selectedId)
  const savedIds=new Set(saved.map((school)=>school.unitId)),aid=profile?calculateProfileAid(profile):undefined
  const toggleSaved=async(school:SchoolRecord)=>{try{if(savedIds.has(school.unitId)){await savedSchoolRepository.remove(school.unitId);setNotice(`${school.name} removed.`)}else{await savedSchoolRepository.save(school.unitId,scorecardSnapshot.metadata.snapshotVersion);setNotice(`${school.name} saved locally.`)}}catch(error){setNotice(error instanceof SavedSchoolLimitError?error.message:'Unable to update saved schools.')}}
  return <PageShell eyebrow="Schools" title="Explore published school costs and outcomes." intro="Search a versioned College Scorecard development fixture. School data is bundled with the app; your household information never enters a school-data request.">
    <div className="rounded-lg border border-line bg-gold-100 p-4 text-sm"><strong>Development fixture:</strong> {scorecardSnapshot.metadata.recordCount} schools from the {scorecardSnapshot.metadata.scorecardDataYear}. This is not the full national College Scorecard dataset.</div>
    <section className="card mt-6 p-6" aria-labelledby="school-search-heading"><h2 id="school-search-heading" className="font-serif text-2xl font-bold">Find a school</h2><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_12rem]"><label className="grid gap-2 text-sm font-bold">Institution name<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Try Ohio or Technology" className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"/></label><label className="grid gap-2 text-sm font-bold">State<select value={state} onChange={(event)=>setState(event.target.value)} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="">All states</option>{[...new Set(scorecardSnapshot.records.map((school)=>school.state))].sort().map((code)=><option key={code} value={code}>{code}</option>)}</select></label></div>
      <p className="mt-4 text-sm text-ink-700">{results.length} result{results.length===1?'':'s'}</p>{results.length===0?<p className="mt-4 rounded-lg bg-moss-100 p-4">No schools match that name and state.</p>:<ul className="mt-3 grid gap-3">{results.map((school)=><li key={school.unitId} className="flex flex-wrap items-center justify-between gap-4 rounded-lg border border-line p-4"><div><p className="font-bold">{school.name}</p><p className="text-sm text-ink-700">{school.state} · {school.control.replaceAll('_',' ')} · UNITID {school.unitId}</p></div><div className="flex gap-2"><button className="button-secondary" type="button" onClick={()=>setSelectedId(school.unitId)}>View details</button><button className="button-primary" type="button" onClick={()=>toggleSaved(school)}>{savedIds.has(school.unitId)?'Remove':'Save'}</button></div></li>)}</ul>}</section>
    <p className="mt-4 min-h-6 text-sm font-bold text-moss-700" role="status">{notice}</p>
    {selected?<SchoolDetails school={selected} aid={aid}/>:null}
    <section className="card mt-6 p-6"><h2 className="font-serif text-2xl font-bold">Saved schools <span className="text-base font-normal">({saved.length}/{SAVED_SCHOOL_LIMIT})</span></h2>{saved.length===0?<p className="mt-3 text-ink-700">No schools saved on this device.</p>:<ul className="mt-4 grid gap-3">{saved.map((entry)=>{const school=scorecardSnapshot.records.find((item)=>item.unitId===entry.unitId);return school?<li key={entry.unitId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-moss-100 p-4"><button type="button" className="font-bold text-moss-700 underline" onClick={()=>setSelectedId(school.unitId)}>{school.name}</button><button type="button" className="button-secondary" onClick={()=>toggleSaved(school)}>Remove</button></li>:<li key={entry.unitId}>School unavailable in snapshot {entry.snapshotVersion}.</li>})}</ul>}</section>
  </PageShell>
}

function SchoolDetails({school,aid}:{school:SchoolRecord;aid:ReturnType<typeof calculateProfileAid>|undefined}){
  const values=getComparableSchoolValues(school)
  return <section className="card mt-6 p-6 sm:p-8" aria-labelledby="school-detail-heading"><p className="eyebrow">School details</p><h2 id="school-detail-heading" className="mt-2 font-serif text-3xl font-bold">{school.name}</h2><p className="mt-2 text-sm text-ink-700">College Scorecard UNITID {school.unitId} · {school.dataYear}</p>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Published cost of attendance" value={formatScorecardMoney(values.publishedCost)}/><Metric label="Tuition and fees — in state" value={formatScorecardMoney(school.tuitionInState)}/><Metric label="Tuition and fees — out of state" value={formatScorecardMoney(school.tuitionOutOfState)}/><Metric label="College Scorecard average net price" value={formatScorecardMoney(values.averageNetPrice)}/><Metric label="Graduation rate" value={formatScorecardPercent(values.graduationRate)}/><Metric label="Scorecard median federal debt" value={formatScorecardMoney(values.medianFederalDebt)}/></div>
    <h3 className="mt-7 font-serif text-xl font-bold">Average net price by federal income bracket</h3><dl className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(school.averageNetPriceByIncome).map(([bracket,value])=><div key={bracket} className="flex justify-between gap-4 rounded-lg bg-moss-100 px-4 py-3"><dt>${bracket.replace('-', '–')}</dt><dd className="font-bold">{formatScorecardMoney(value)}</dd></div>)}</dl>
    <h3 className="mt-7 font-serif text-xl font-bold">Earnings outcomes</h3>{school.earnings.length?<dl className="mt-3 grid gap-3">{school.earnings.map((outcome)=><div key={outcome.label} className="rounded-lg bg-moss-100 p-4"><dt>{outcome.label}</dt><dd className="mt-1 font-bold">{formatScorecardMoney(outcome.value)}</dd></div>)}</dl>:<p className="mt-3">Not available.</p>}
    <div className="mt-7 rounded-lg border border-line p-5"><h3 className="font-serif text-xl font-bold">Your federal estimate stays separate</h3>{aid?.status==='calculated'?<p className="mt-3">Your locally calculated SAI is <strong>{aid.sai.sai.toLocaleString()}</strong>{aid.pell.status==='eligible'?<> and your Pell Scheduled Award estimate is <strong>{formatScorecardMoney(aid.pell.scheduledAward)}</strong></>:null}. These values are not subtracted here to claim an exact school net price.</p>:<p className="mt-3">Complete a supported dependent-student household profile to see the separate federal SAI/Pell estimate.</p>}<p className="mt-3 text-sm">College Scorecard average net price is a historical average, not your personalized aid offer. Institutional aid varies substantially, and the school’s financial-aid office provides the actual offer.</p></div>
  </section>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-moss-100 p-4"><p className="text-sm text-ink-700">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
