import { useState, type FormEvent } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { EMPTY_CALCULATION_PROFILE, FICTIONAL_DEMO_PROFILE } from '../lib/storage/demoProfile'
import { navigatorDatabase } from '../lib/storage/database'
import { householdRepository } from '../lib/storage/repositories'
import type { CalculationProfile, HouseholdProfileInput } from '../lib/storage/schema'

type StoredBusinessAsset = NonNullable<CalculationProfile['parentAssets']>['businessFarmAssets'][number]

const EMPTY_PROFILE: HouseholdProfileInput = { studentName:'',householdName:'',dependencyStatus:'dependent',awardYear:'2026-27',familySize:2,state:'',isFictionalDemo:false,calculation:null }
const incomeFields = [
  ['agi','Adjusted gross income'],['deductiblePayments','Deductible IRA/KEOGH/qualified-plan payments'],['taxExemptInterest','Tax-exempt interest'],
  ['untaxedIraDistributions','Untaxed IRA distributions'],['iraRollover','IRA rollover'],['untaxedPensions','Untaxed pensions'],['pensionRollover','Pension rollover'],
  ['foreignIncomeExclusion','Foreign income exclusion'],['taxableGrants','Taxable grants/scholarships'],['educationCredits','Education credits'],
  ['federalWorkStudy','Federal Work-Study'],['incomeTaxPaid','Income tax paid'],
] as const
const benefits = [['EITC','EITC'],['HOUSING_ASSISTANCE','Federal housing assistance'],['SCHOOL_LUNCH','Free/reduced-price school lunch'],['MEDICAID','Medicaid'],['QHP_CREDIT','Refundable QHP credit'],['SNAP','SNAP'],['SSI','SSI'],['TANF','TANF'],['WIC','WIC']] as const

const money = (value: string) => value === '' ? 0 : Number(value)
export function HouseholdProfileForm() {
  const savedProfile = useLiveQuery(() => navigatorDatabase.profiles.get('current-household'))
  const [draft,setDraft] = useState<HouseholdProfileInput>(EMPTY_PROFILE)
  const [status,setStatus] = useState('No profile loaded.')
  const setField = <K extends keyof HouseholdProfileInput>(key:K,value:HouseholdProfileInput[K]) => setDraft((current) => ({...current,[key]:value,isFictionalDemo:false}))
  const setCalc = (update:(calculation:CalculationProfile)=>CalculationProfile) => setDraft((current) => ({...current,calculation:update(current.calculation ?? structuredClone(EMPTY_CALCULATION_PROFILE)),isFictionalDemo:false}))
  const setIncome = (person:'parentIncome'|'studentIncome',key:string,value:number) => setCalc((c) => ({...c,[person]:{...c[person],[key]:value}}))
  const setAsset = (person:'parentAssets'|'studentAssets',key:string,value:number) => setCalc((c) => ({...c,[person]:{...c[person]!,[key]:value}}))
  const loadDemo = () => { setDraft(structuredClone(FICTIONAL_DEMO_PROFILE)); setStatus('Fictional demo loaded. Choose Save profile to keep it in this browser.') }
  const loadSaved = async () => { const profile=await householdRepository.load(); if(!profile){setStatus('No saved profile found in this browser.');return} const {id:_id,updatedAt:_updatedAt,schemaVersion:_schemaVersion,...input}=profile; setDraft(input); setStatus('Saved profile loaded from this browser.') }
  const save = async (event:FormEvent) => { event.preventDefault(); try{await householdRepository.save(draft);setStatus('Profile saved locally in this browser.')}catch{setStatus('Check the highlighted fields before saving.')} }
  const calculation=draft.calculation

  return <section className="card p-6 sm:p-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Local household profile</p><h2 className="mt-2 font-serif text-2xl font-bold">2026–27 household inputs</h2></div>{savedProfile?<span className="rounded-full bg-moss-100 px-3 py-1 text-xs font-bold text-moss-700">Saved locally</span>:null}</div>
    <p className="mt-3 text-sm leading-6 text-ink-700">Stored only in IndexedDB on this device. Financial values are never sent over the network.</p>
    <div className="mt-5 flex flex-wrap gap-3"><button type="button" className="button-secondary" onClick={loadDemo}>Load fictional demo</button><button type="button" className="button-secondary" onClick={loadSaved}>Load saved profile</button></div>
    <form className="mt-6 grid gap-5" onSubmit={save}>
      <div className="grid gap-5 sm:grid-cols-2">
        <Text label="Student name" value={draft.studentName} onChange={(v)=>setField('studentName',v)}/><Text label="Household label" value={draft.householdName} onChange={(v)=>setField('householdName',v)}/>
        <Text label="State or location" value={draft.state} onChange={(v)=>setField('state',v)}/><NumberField label="Family size" min={2} value={draft.familySize} onChange={(v)=>setField('familySize',v)}/>
        <label className="grid gap-2 text-sm font-bold">Dependency status<select value={draft.dependencyStatus} onChange={(e)=>setField('dependencyStatus',e.target.value as 'dependent'|'independent')} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="dependent">Dependent — Formula A</option><option value="independent">Independent — unsupported in v1</option></select></label>
      </div>
      {!calculation?<div className="rounded-lg bg-gold-100 p-5"><p className="font-bold">Financial details are incomplete</p><p className="mt-2 text-sm">Add all required federal worksheet inputs to calculate an estimate. Zeros are explicit values, not guesses.</p><button type="button" className="button-secondary mt-4" onClick={()=>setCalc((c)=>c)}>Add financial details</button></div>:<>
        <fieldset className="grid gap-4 rounded-lg border border-line p-5"><legend className="px-2 font-serif text-xl font-bold">Household and Pell facts</legend><div className="grid gap-4 sm:grid-cols-3"><NumberField label="Number in college (informational only)" min={1} value={calculation.numberInCollege} onChange={(v)=>setCalc((c)=>({...c,numberInCollege:v}))}/><NumberField label="Pell cost of attendance" min={0} value={calculation.pellCoa} onChange={(v)=>setCalc((c)=>({...c,pellCoa:v}))}/><label className="grid gap-2 text-sm font-bold">Max Pell indicator<select value={calculation.maxPellIndicator} onChange={(e)=>setCalc((c)=>({...c,maxPellIndicator:Number(e.target.value) as 0|1|2|3}))} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="0">None</option><option value="1">1 — qualifying nonfiler</option><option value="2">2</option><option value="3">3</option></select></label></div><Checks values={[
          ['Single-parent household',calculation.parentSingleParent,(v)=>setCalc((c)=>({...c,parentSingleParent:v}))],['Qualifying parent nonfiler',calculation.qualifyingParentNonfiler,(v)=>setCalc((c)=>({...c,qualifyingParentNonfiler:v}))],['Possible statutory special-rule dependent',calculation.possibleSpecialRuleDependent,(v)=>setCalc((c)=>({...c,possibleSpecialRuleDependent:v}))],
        ]}/></fieldset>
        {(['parentIncome','studentIncome'] as const).map((person)=><fieldset key={person} className="rounded-lg border border-line p-5"><legend className="px-2 font-serif text-xl font-bold">{person==='parentIncome'?'Parent':'Student'} income and offsets</legend><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{incomeFields.map(([key,label])=><NumberField key={key} label={label} value={calculation[person][key]} onChange={(v)=>setIncome(person,key,v)}/>)}<NumberField label="Income earned from work" value={calculation[person].workReturns[0].workIncome} onChange={(v)=>setCalc((c)=>({...c,[person]:{...c[person],workReturns:[{...c[person].workReturns[0],workIncome:v}]}}))}/><label className="grid gap-2 text-sm font-bold">Tax filing status<select value={calculation[person].workReturns[0].filingStatus} onChange={(e)=>setCalc((c)=>({...c,[person]:{...c[person],workReturns:[{...c[person].workReturns[0],filingStatus:e.target.value as CalculationProfile[typeof person]['workReturns'][number]['filingStatus']}]}}))} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="single">Single</option><option value="head_of_household">Head of household</option><option value="qualifying_surviving_spouse">Qualifying surviving spouse</option><option value="married_filing_jointly">Married filing jointly</option><option value="married_filing_separately">Married filing separately</option><option value="dependent_student">Dependent student</option></select></label></div></fieldset>)}
        <fieldset className="rounded-lg border border-line p-5"><legend className="px-2 font-serif text-xl font-bold">Asset-reporting and filing facts</legend><Checks values={[
          ['Qualifies for Maximum Pell',calculation.assetExemption.qualifiesForMaximumPell,(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,qualifiesForMaximumPell:v}}))],['Filed Schedule A, B, D, E, F, or H',calculation.assetExemption.filedSchedulesA_B_D_E_F_H,(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,filedSchedulesA_B_D_E_F_H:v}}))],['Received a listed means-tested benefit',calculation.assetExemption.receivedMeansTestedBenefit,(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,receivedMeansTestedBenefit:v}}))],['Parents live outside the U.S.',calculation.assetExemption.parentsLiveOutsideUs,(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,parentsLiveOutsideUs:v}}))],['Parents filed a U.S./territory return',calculation.assetExemption.parentsFiledUsOrTerritoryReturn,(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,parentsFiledUsOrTerritoryReturn:v}}))],['Nonfiling because income was below threshold',calculation.assetExemption.nonfilingBelowFilingThreshold,(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,nonfilingBelowFilingThreshold:v}}))],
        ]}/><div className="mt-4 grid gap-4 sm:grid-cols-3"><NumberField label="Parent AGI for asset gate" value={calculation.assetExemption.parentAgi} onChange={(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,parentAgi:v}}))}/><label className="grid gap-2 text-sm font-bold">Schedule C<select value={calculation.assetExemption.scheduleC} onChange={(e)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,scheduleC:e.target.value as 'filed'|'not_filed'}}))} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="not_filed">Not filed</option><option value="filed">Filed</option></select></label><NumberField label="Schedule C net income/loss" value={calculation.assetExemption.scheduleCNetIncome??0} onChange={(v)=>setCalc((c)=>({...c,assetExemption:{...c.assetExemption,scheduleCNetIncome:v}}))}/></div><div className="mt-5"><p className="text-sm font-bold">Means-tested benefits received in 2024 or 2025</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{benefits.map(([value,label])=><label key={value} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={calculation.meansTestedBenefits2024or2025.includes(value)} onChange={(e)=>setCalc((c)=>({...c,meansTestedBenefits2024or2025:e.target.checked?[...c.meansTestedBenefits2024or2025,value]:c.meansTestedBenefits2024or2025.filter((x)=>x!==value)}))}/>{label}</label>)}</div></div></fieldset>
        {(['parentAssets','studentAssets'] as const).map((person)=><fieldset key={person} className="rounded-lg border border-line p-5"><legend className="px-2 font-serif text-xl font-bold">{person==='parentAssets'?'Parent':'Student'} assets</legend><div className="grid gap-4 sm:grid-cols-3">{person==='parentAssets'?<NumberField label="Annual child support received" value={calculation[person]!.annualChildSupportReceived} onChange={(v)=>setAsset(person,'annualChildSupportReceived',v)}/>:null}<NumberField label="Cash, savings, and checking" value={calculation[person]!.cashSavingsChecking} onChange={(v)=>setAsset(person,'cashSavingsChecking',v)}/><NumberField label="Investment net worth" value={calculation[person]!.investmentNetWorth} onChange={(v)=>setAsset(person,'investmentNetWorth',v)}/></div><BusinessAssetFields items={calculation[person]!.businessFarmAssets} onChange={(businessFarmAssets)=>setCalc((c)=>({...c,[person]:{...c[person]!,businessFarmAssets}}))}/></fieldset>)}
        <button type="button" className="button-secondary justify-self-start" onClick={()=>setField('calculation',null)}>Remove financial details</button>
      </>}
      <div className="flex flex-wrap items-center gap-4"><button type="submit" className="button-primary">Save profile</button><p role="status" className="text-sm text-ink-700">{status}</p></div>
    </form>
  </section>
}

function Text({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) { return <label className="grid gap-2 text-sm font-bold">{label}<input required maxLength={80} value={value} onChange={(e)=>onChange(e.target.value)} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"/></label> }
function NumberField({label,value,onChange,min}:{label:string;value:number;onChange:(value:number)=>void;min?:number}) { return <label className="grid gap-2 text-sm font-bold">{label}<input required type="number" min={min} step="1" value={value} onChange={(e)=>onChange(money(e.target.value))} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"/></label> }
function Checks({values}:{values:Array<[string,boolean,(value:boolean)=>void]>}) { return <div className="grid gap-3 sm:grid-cols-2">{values.map(([label,checked,onChange])=><label key={label} className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/><span>{label}</span></label>)}</div> }
function BusinessAssetFields({items,onChange}:{items:StoredBusinessAsset[];onChange:(items:StoredBusinessAsset[])=>void}) {
  const initial:StoredBusinessAsset={netWorth:0,category:'other',familyOwnedOrControlled:false}
  const update=(index:number,item:StoredBusinessAsset)=>onChange(items.map((current,i)=>i===index?item:current))
  return <div>{items.map((item,index)=><div key={index} className="mt-5 grid gap-4 rounded-lg bg-moss-100 p-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Business/farm net worth" value={item.netWorth} onChange={(netWorth)=>update(index,{...item,netWorth})}/><label className="grid gap-2 text-sm font-bold">Asset category<select value={item.category} onChange={(e)=>update(index,{...item,category:e.target.value as StoredBusinessAsset['category']})} className="rounded-lg border border-line bg-white px-3 py-2.5 font-normal"><option value="family_business">Family business</option><option value="family_residence_farm">Family residence farm</option><option value="family_commercial_fishing">Family commercial fishing</option><option value="other">Other reportable business/farm</option></select></label><NumberField label="Full-time-equivalent employees" min={0} value={item.fullTimeEquivalentEmployees??0} onChange={(fullTimeEquivalentEmployees)=>update(index,{...item,fullTimeEquivalentEmployees})}/><div className="flex flex-col gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.familyOwnedOrControlled} onChange={(e)=>update(index,{...item,familyOwnedOrControlled:e.target.checked})}/>Family owned/controlled</label><button type="button" className="button-secondary" onClick={()=>onChange(items.filter((_,i)=>i!==index))}>Remove asset</button></div></div>)}<button type="button" className="button-secondary mt-4" onClick={()=>onChange([...items,initial])}>Add business, farm, or fishing asset</button></div>
}
