import { useState, type FormEvent } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { EMPTY_CALCULATION_PROFILE, FICTIONAL_DEMO_PROFILE } from '../lib/storage/demoProfile'
import { householdRepository } from '../lib/storage/repositories'
import type { CalculationDraft, HouseholdProfileInput } from '../lib/storage/schema'
import { residences } from '../lib/residence'

type BusinessAsset=NonNullable<NonNullable<CalculationDraft['parentAssets']>['businessFarmAssets']>[number]
const EMPTY_PROFILE:HouseholdProfileInput={studentName:'',householdName:'',dependencyStatus:'dependent',awardYear:'2026-27',familySize:null,state:'',isFictionalDemo:false,calculation:null}
const incomeFields=[['agi','Adjusted gross income'],['deductiblePayments','Deductible IRA/KEOGH/qualified-plan payments'],['taxExemptInterest','Tax-exempt interest'],['untaxedIraDistributions','Untaxed IRA distributions'],['iraRollover','IRA rollover'],['untaxedPensions','Untaxed pensions'],['pensionRollover','Pension rollover'],['foreignIncomeExclusion','Foreign income exclusion'],['taxableGrants','Taxable grants/scholarships'],['educationCredits','Education credits'],['federalWorkStudy','Federal Work-Study'],['incomeTaxPaid','Income tax paid']] as const
const benefits=['EITC','HOUSING_ASSISTANCE','SCHOOL_LUNCH','MEDICAID','QHP_CREDIT','SNAP','SSI','TANF','WIC'] as const
const filingStatuses=['single','head_of_household','qualifying_surviving_spouse','married_filing_jointly','married_filing_separately','dependent_student'] as const

export function HouseholdProfileForm(){
  const saved=useLiveQuery(()=>householdRepository.load())
  const [draft,setDraft]=useState<HouseholdProfileInput>(EMPTY_PROFILE),[status,setStatus]=useState('No profile loaded.')
  const setField=<K extends keyof HouseholdProfileInput>(key:K,value:HouseholdProfileInput[K])=>setDraft(current=>({...current,[key]:value,isFictionalDemo:false}))
  const setCalc=(update:(c:CalculationDraft)=>CalculationDraft)=>setDraft(current=>({...current,calculation:update(current.calculation??structuredClone(EMPTY_CALCULATION_PROFILE)),isFictionalDemo:false}))
  const loadSaved=async()=>{try{const profile=await householdRepository.load();if(!profile){setStatus('No saved profile found in this browser.');return}setDraft(profile);setStatus('Saved profile loaded from this browser.')}catch{setStatus('Saved data is unavailable or invalid. Check browser storage or restore a valid backup.')}}
  const save=async(event:FormEvent)=>{event.preventDefault();try{await householdRepository.save(draft);setStatus('Profile saved locally in this browser.')}catch{setStatus('Unable to save. Review the required fields and browser storage permissions.')}}
  const c=draft.calculation
  return <section className="card p-6 sm:p-8">
    <h2 className="font-serif text-2xl font-bold">2026–27 household inputs</h2>{saved?<p className="text-sm">Saved locally</p>:null}
    <p className="mt-3 text-sm">Stored only in IndexedDB on this device. Financial values are never sent over the network. Blank or unknown answers do not mean zero or no. You may save an incomplete profile.</p>
    <div className="mt-5 flex flex-wrap gap-3"><button type="button" className="button-secondary" onClick={()=>{setDraft(structuredClone(FICTIONAL_DEMO_PROFILE));setStatus('Fictional demo loaded. Choose Save profile to keep it in this browser.')}}>Load fictional demo</button><button type="button" className="button-secondary" onClick={loadSaved}>Load saved profile</button></div>
    {draft.legacyProfile!==undefined?<details className="mt-4 rounded border p-4"><summary>Prior-version inputs retained for review</summary><p className="mt-3 text-sm">The old app did not distinguish unanswered defaults from confirmed answers. Re-enter the answers you can verify below. The original record is retained locally and in your backup; it is not used for estimates.</p><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(draft.legacyProfile,null,2)}</pre></details>:null}
    <form className="mt-6 grid gap-5" onSubmit={save}>
      <div className="grid gap-5 sm:grid-cols-2"><Text label="Student name" value={draft.studentName} change={value=>setField('studentName',value)}/><Text label="Household label" value={draft.householdName} change={value=>setField('householdName',value)}/>
        <label className="grid gap-2 text-sm font-bold">State or location<select required value={draft.state} onChange={e=>setField('state',e.target.value)}><option value="">Choose location</option>{Object.entries(residences).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label>
        <NumberField label="Family size" value={draft.familySize} min={2} change={value=>setField('familySize',value)}/>
        <label className="grid gap-2 text-sm font-bold">Dependency status<select value={draft.dependencyStatus} onChange={e=>setField('dependencyStatus',e.target.value as 'dependent'|'independent')}><option value="dependent">Dependent — Formula A</option><option value="independent">Independent — unsupported in v1</option></select></label>
      </div>
      {!c?<div className="rounded-lg bg-gold-100 p-5"><p className="font-bold">Financial details are incomplete</p><button type="button" className="button-secondary mt-4" onClick={()=>setCalc(value=>value)}>Add financial details</button></div>:<>
        <fieldset className="rounded-lg border p-5"><legend>Household and Pell facts</legend><div className="grid gap-4 sm:grid-cols-2">
          <NumberField label="Number in college (informational only)" value={c.numberInCollege} min={1} change={value=>{if(value!==null)setCalc(x=>({...x,numberInCollege:value}))}}/>
          <NumberField label="Pell cost of attendance" value={c.pellCoa} min={0} change={value=>setCalc(x=>({...x,pellCoa:value}))}/>
          <Answer label="Single-parent household" value={c.parentSingleParent} change={value=>setCalc(x=>({...x,parentSingleParent:value}))}/>
          <Answer label="Qualifying parent nonfiler (not required to file)" value={c.qualifyingParentNonfiler} change={value=>setCalc(x=>({...x,qualifyingParentNonfiler:value}))}/>
          <Answer label="Possible statutory special-rule dependent" value={c.possibleSpecialRuleDependent} change={value=>setCalc(x=>({...x,possibleSpecialRuleDependent:value}))}/>
        </div><p className="mt-3 text-sm">Maximum Pell indicators and asset-exemption eligibility are derived from your answers, not entered separately.</p></fieldset>
        {(['parentIncome','studentIncome'] as const).map(person=><fieldset key={person} className="rounded-lg border p-5"><legend>{person==='parentIncome'?'Parent':'Student'} income and offsets</legend><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {incomeFields.map(([key,label])=><NumberField key={key} label={label} value={c[person][key]} change={value=>setCalc(x=>({...x,[person]:{...x[person],[key]:value}}))}/>)}
        </div>{c[person].workReturns.map((entry,index)=><fieldset key={index} className="mt-4 rounded border p-3"><legend>{person==='parentIncome'?'Parent':'Student'} tax return {index+1}</legend>
          <NumberField label="Income earned from work" value={entry.workIncome} change={value=>setCalc(x=>({...x,[person]:{...x[person],workReturns:x[person].workReturns.map((r,i)=>i===index?{...r,workIncome:value}:r)}}))}/>
          <label className="mt-3 grid gap-2 text-sm font-bold">Tax filing status<select value={entry.filingStatus??''} onChange={e=>setCalc(x=>({...x,[person]:{...x[person],workReturns:x[person].workReturns.map((r,i)=>i===index?{...r,filingStatus:e.target.value===''?null:e.target.value as typeof filingStatuses[number]}:r)}}))}><option value="">Unknown</option>{filingStatuses.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label>
          {c[person].workReturns.length>1?<button type="button" className="button-secondary mt-3" onClick={()=>setCalc(x=>({...x,[person]:{...x[person],workReturns:x[person].workReturns.filter((_,i)=>i!==index)}}))}>Remove tax return {index+1}</button>:null}
        </fieldset>)}{c[person].workReturns.length<2?<button type="button" className="button-secondary mt-3" onClick={()=>setCalc(x=>({...x,[person]:{...x[person],workReturns:[...x[person].workReturns,{filingStatus:null,workIncome:null}]}}))}>Add {person==='parentIncome'?'parent':'student'} tax return</button>:null}</fieldset>)}
        <fieldset className="rounded-lg border p-5"><legend>Asset-reporting and filing facts</legend><div className="grid gap-4 sm:grid-cols-2">
          {([['filedSchedulesA_B_D_E_F_H','Filed Schedule A, B, D, E, F, or H'],['parentsLiveOutsideUs','Parents live outside the U.S.'],['parentsFiledUsOrTerritoryReturn','Parents filed a U.S./territory return'],['nonfilingBelowFilingThreshold','Nonfiling because income was below threshold']] as const).map(([key,label])=><Answer key={key} label={label} value={c.assetExemption[key]} change={value=>setCalc(x=>({...x,assetExemption:{...x.assetExemption,[key]:value}}))}/>)}
          <label className="grid gap-2 text-sm font-bold">Schedule C<select value={c.assetExemption.scheduleC??''} onChange={e=>setCalc(x=>({...x,assetExemption:{...x.assetExemption,scheduleC:e.target.value===''?null:e.target.value as 'filed'|'not_filed'}}))}><option value="">Unknown</option><option value="not_filed">Not filed</option><option value="filed">Filed</option></select></label>
          {c.assetExemption.scheduleC==='filed'?<NumberField label="Schedule C net income/loss" value={c.assetExemption.scheduleCNetIncome??null} change={value=>setCalc(x=>({...x,assetExemption:{...x.assetExemption,scheduleCNetIncome:value}}))}/>:null}
        </div><p className="mt-4 font-bold">Means-tested benefits received in 2024 or 2025</p>
        <Answer label="Benefits list is complete (including none)" value={c.meansTestedBenefits2024or2025===null?null:true} change={value=>setCalc(x=>({...x,meansTestedBenefits2024or2025:value===true?(x.meansTestedBenefits2024or2025??[]):null}))}/>
        {c.meansTestedBenefits2024or2025!==null?<div className="mt-3 grid gap-2 sm:grid-cols-3">{benefits.map(value=><label key={value}><input type="checkbox" checked={c.meansTestedBenefits2024or2025!.includes(value)} onChange={e=>setCalc(x=>({...x,meansTestedBenefits2024or2025:e.target.checked?[...(x.meansTestedBenefits2024or2025??[]),value]:(x.meansTestedBenefits2024or2025??[]).filter(item=>item!==value)}))}/> {value.replaceAll('_',' ')}</label>)}</div>:null}
        </fieldset>
        {(['parentAssets','studentAssets'] as const).map(person=>{const assets=c[person];return <fieldset key={person} className="rounded-lg border p-5"><legend>{person==='parentAssets'?'Parent':'Student'} assets</legend>{!assets?<><p className="text-sm">Not supplied. Assets are not required when the household qualifies for exemption.</p><button type="button" className="button-secondary mt-3" onClick={()=>setCalc(x=>({...x,[person]:{...(person==='parentAssets'?{annualChildSupportReceived:null}:{}),cashSavingsChecking:null,investmentNetWorth:null,businessFarmAssets:null}}))}>Add {person==='parentAssets'?'parent':'student'} asset details</button></>:<>
          <div className="grid gap-4 sm:grid-cols-3">{person==='parentAssets'?<NumberField label="Annual child support received" value={c.parentAssets!.annualChildSupportReceived} change={value=>setCalc(x=>({...x,parentAssets:{...x.parentAssets!,annualChildSupportReceived:value}}))}/>:null}
          {([['cashSavingsChecking','Cash, savings, and checking'],['investmentNetWorth','Investment net worth']] as const).map(([key,label])=><NumberField key={key} label={label} value={assets[key]} change={value=>setCalc(x=>({...x,[person]:{...x[person]!,[key]:value}}))}/>)}</div>
          <Answer label="Business/farm list is complete (including none)" value={assets.businessFarmAssets===null?null:true} change={value=>setCalc(x=>({...x,[person]:{...x[person]!,businessFarmAssets:value===true?(x[person]!.businessFarmAssets??[]):null}}))}/>
          {assets.businessFarmAssets!==null?<BusinessAssetFields items={assets.businessFarmAssets} change={value=>setCalc(x=>({...x,[person]:{...x[person]!,businessFarmAssets:value}}))}/>:null}
          <button type="button" className="button-secondary mt-3" onClick={()=>setCalc(x=>({...x,[person]:undefined}))}>Remove {person==='parentAssets'?'parent':'student'} asset details</button>
        </>}</fieldset>})}
        <button type="button" className="button-secondary justify-self-start" onClick={()=>setField('calculation',null)}>Remove financial details</button>
      </>}
      <div className="flex flex-wrap items-center gap-4"><button type="submit" className="button-primary">Save profile</button><p role="status" className="text-sm">{status}</p></div>
    </form>
  </section>
}

function Text({label,value,change}:{label:string;value:string;change:(value:string)=>void}){return <label className="grid gap-2 text-sm font-bold">{label}<input required maxLength={80} value={value} onChange={e=>change(e.target.value)} className="rounded-lg border px-3 py-2.5 font-normal"/></label>}
function NumberField({label,value,change,min}:{label:string;value:number|null;change:(value:number|null)=>void;min?:number}){return <label className="grid gap-2 text-sm font-bold">{label}<input type="number" min={min} step="any" value={value??''} placeholder="Unknown" onChange={e=>change(e.target.value===''?null:Number(e.target.value))} className="rounded-lg border px-3 py-2.5 font-normal"/></label>}
function Answer({label,value,change}:{label:string;value:boolean|null;change:(value:boolean|null)=>void}){return <label className="mt-3 grid gap-2 text-sm font-bold">{label}<select value={value===null?'':String(value)} onChange={e=>change(e.target.value===''?null:e.target.value==='true')} className="rounded-lg border px-3 py-2.5 font-normal"><option value="">Unknown</option><option value="true">Yes</option><option value="false">No</option></select></label>}
function BusinessAssetFields({items,change}:{items:BusinessAsset[];change:(items:BusinessAsset[])=>void}){
  const update=(index:number,item:BusinessAsset)=>change(items.map((current,i)=>i===index?item:current))
  return <div>{items.map((item,index)=><fieldset key={index} className="mt-4 rounded border p-3"><legend>Business/farm {index+1}</legend><NumberField label="Business/farm net worth" value={item.netWorth} change={value=>update(index,{...item,netWorth:value})}/><label className="mt-3 grid gap-2">Asset category<select value={item.category} onChange={e=>update(index,{...item,category:e.target.value as BusinessAsset['category']})}><option value="family_business">Family business</option><option value="family_residence_farm">Family residence farm</option><option value="family_commercial_fishing">Family commercial fishing</option><option value="other">Other reportable business/farm</option></select></label><NumberField label="Full-time-equivalent employees" value={item.fullTimeEquivalentEmployees??null} min={0} change={value=>update(index,{...item,fullTimeEquivalentEmployees:value})}/><Answer label="Family owned/controlled" value={item.familyOwnedOrControlled} change={value=>update(index,{...item,familyOwnedOrControlled:value})}/><button type="button" className="button-secondary mt-3" onClick={()=>change(items.filter((_,i)=>i!==index))}>Remove asset</button></fieldset>)}<button type="button" className="button-secondary mt-3" onClick={()=>change([...items,{netWorth:null,category:'other',familyOwnedOrControlled:null}])}>Add business, farm, or fishing asset</button></div>
}
