import { render,screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { describe,expect,it,vi } from 'vitest'
import type { PlannerSchoolResult } from '../lib/funding'
import { DecisionSeasonChecklist,FundingTimeline,GraduationCalculationExplanation,PlanCompleteness,RepaymentHandoff,SourceBadge,WhatIfComparison } from './PlannerFinalFeatures'
import { derivePlanCompleteness,sourceKindFor } from './plannerFinalModel'

const metric=(status:'complete'|'partial'|'incomplete',knownCents?:number)=>({status,...(knownCents===undefined?{}:{knownCents}),resolvedYears:status==='complete'?1:0,totalYears:1,reasons:status==='complete'?[]:['Year 1 amount unknown']})
const result={status:'incomplete',school:{unitId:1,name:'Test University'},errors:[{field:'pell-0-status',message:'Year 1 Pell remains unknown.',step:2,year:0}],missingReasons:['Year 1 Pell remains unknown.','Future rate remains unknown.'],metrics:{cost:metric('complete',3_000_000),grants:metric('partial',500_000),familyCash:metric('complete',0),studentGross:metric('complete',100_000),studentNet:metric('complete',98_943),parentPlusGross:metric('complete',0),parentPlusNet:metric('complete',0),fees:metric('complete',1_057),gap:metric('complete',0),surplus:metric('complete',98_943),studentPrincipal:metric('complete',100_000),studentInterest:metric('incomplete'),studentDebt:metric('partial',100_000),parentPrincipal:metric('complete',0),parentInterest:metric('complete',0),parentDebt:metric('complete',0)},funding:{annual:[{year:1,status:'requires_assumption',projectedCostCents:3_000_000,knownNonLoanFundingCents:500_000,partialKnownGapCents:2_500_000,reasons:['Pell unknown']}],funding:[{year:1,status:'requires_assumption',knownFundingCents:500_000,applied:[{entryId:'grant',category:'institutional_grant',label:'Grant',amountCents:500_000,valueStatus:'known',provenance:{source:'School offer'}}],unknown:[{entryId:'pell',category:'pell',label:'Pell',reason:'Unknown'}]}]},allocations:[{status:'complete',elections:{directSubsidizedGrossCents:100_000,directUnsubsidizedGrossCents:0,parentPlusGrossCents:0},accounting:{preLoanGapCents:0,grossBorrowingCents:100_000,originationFeesCents:1_057,netProceedsCents:98_943,studentNetProceedsCents:98_943,parentPlusNetProceedsCents:0,signedRemainingFundingGapCents:-98_943,remainingUncoveredFundingGapCents:0,surplusLoanProceedsCents:98_943}}],graduation:null,futureRateResolutions:[],omittedElectedPrincipalCents:0} as unknown as PlannerSchoolResult

describe('final planner presentation features',()=>{
  it('maps provenance without calling an assumption federal policy',()=>{expect(sourceKindFor('College Scorecard 2023')).toBe('scorecard');expect(sourceKindFor('User planning input','assumed')).toBe('assumption');expect(sourceKindFor('Federal policy table')).toBe('federal');render(<SourceBadge kind="assumption"/>);expect(screen.getByText('Assumption')).toBeVisible()})
  it('updates the factual checklist count with keyboard-operable checkboxes and no judgment',async()=>{const user=userEvent.setup();render(<DecisionSeasonChecklist/>);const first=screen.getByRole('checkbox',{name:'Compare the official financial-aid offer'});first.focus();await user.keyboard('[Space]');expect(screen.getByText('1 of 16 checklist items reviewed')).toBeVisible();expect(document.body).not.toHaveTextContent(/good|bad|score|rating/i)})
  it('derives completeness from adapter states and recovers an actionable item',async()=>{const recover=vi.fn(),user=userEvent.setup(),value=derivePlanCompleteness(result);expect(value.missing.map(item=>item.message)).toEqual(['Year 1 Pell remains unknown.','Future rate remains unknown.']);render(<PlanCompleteness result={result} recover={recover}/>);await user.click(screen.getByRole('button',{name:'Year 1 Pell remains unknown.'}));expect(recover).toHaveBeenCalledWith(result.errors[0])})
  it('renders known, partial, unknown, surplus, and an accessible calculation disclosure',async()=>{const user=userEvent.setup();render(<FundingTimeline result={result}/>);expect(screen.getByText('Funding timeline')).toBeVisible();expect(screen.getByText('→ projected surplus').parentElement).toHaveTextContent('$989');expect(screen.getByText(/Unknown values are not shown as \$0/)).toBeVisible();await user.click(screen.getByText('How was this calculated?'));expect(screen.getByText(/Gross principal − origination fees = net proceeds/)).toBeVisible()})
  it('shows factual what-if differences without a winner or recommendation',()=>{const alternate=structuredClone(result);alternate.metrics.cost.knownCents=3_100_000;render(<WhatIfComparison baseline={[result]} current={[alternate]}/>);expect(screen.getByText('Difference +$1,000')).toBeVisible();expect(document.body).toHaveTextContent('No scenario is ranked or recommended');expect(document.body).not.toHaveTextContent(/winner|better|worse/i)})
  it('explains graduation debt without inventing capitalization when facts are incomplete',async()=>{const user=userEvent.setup();render(<GraduationCalculationExplanation results={[result]}/>);await user.click(screen.getByText('How was this calculated?'));expect(screen.getByText(/no unavailable amount is converted to \$0/i)).toBeVisible();expect(screen.getByText('Capitalization is not applied in this graduation snapshot.')).toBeVisible()})
  it('keeps repayment handoff manual and free of financial URL state',()=>{render(<MemoryRouter><RepaymentHandoff/></MemoryRouter>);const link=screen.getByRole('link',{name:'Explore repayment scenarios'});expect(link).toHaveAttribute('href','/app/repayment');expect(link.getAttribute('href')).not.toContain('?');expect(screen.getByText(/or transferred automatically/)).toBeVisible()})
})
