import { useState } from 'react'
import { compareAidScenario,createAidScenario,updateAidScenario,type AidScenarioField } from '../lib/aidScenario'
import { householdRepository } from '../lib/storage/repositories'
import type { HouseholdProfile } from '../lib/storage/schema'

const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value)
const signed=(value:number,format:(value:number)=>string)=>(value>0?'+':'')+format(value)

export function ScenarioWorkspace({profile}:{profile:HouseholdProfile}){
  const [active,setActive]=useState(false),[scenario,setScenario]=useState(()=>createAidScenario(profile)),[notice,setNotice]=useState('')
  if(!active)return <section className="card mt-6 p-5 sm:p-6"><h2 className="font-serif text-2xl font-bold">Explore a what-if scenario</h2><p className="mt-3 text-sm">Change a copy of selected aid inputs to see sensitivity. Your saved profile is not changed unless you explicitly apply the scenario.</p><button type="button" className="button-secondary mt-4" onClick={()=>{setScenario(createAidScenario(profile));setActive(true)}}>Start a what-if scenario</button></section>
  const comparison=compareAidScenario(profile,scenario)
  const update=(field:AidScenarioField,value:number|null)=>setScenario(current=>updateAidScenario(current,field,value))
  return <section className="card mt-6 p-5 sm:p-6" aria-labelledby="scenario-heading"><h2 id="scenario-heading" className="font-serif text-2xl font-bold">Aid what-if scenario</h2><p className="mt-3 text-sm">Educational sensitivity only—not tax or financial advice. Unknown or contradictory inputs fail closed instead of producing a guess.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><ScenarioNumber label="Scenario parent AGI" value={scenario.calculation?.parentIncome.agi??null} change={value=>update('parentAgi',value)}/><ScenarioNumber label="Scenario student AGI" value={scenario.calculation?.studentIncome.agi??null} change={value=>update('studentAgi',value)}/>{scenario.calculation?.parentAssets?<ScenarioNumber label="Scenario parent cash, savings, and checking" value={scenario.calculation.parentAssets.cashSavingsChecking} change={value=>update('parentCash',value)}/>:null}{scenario.calculation?.studentAssets?<ScenarioNumber label="Scenario student cash, savings, and checking" value={scenario.calculation.studentAssets.cashSavingsChecking} change={value=>update('studentCash',value)}/>:null}</div><ScenarioResults comparison={comparison}/><div className="mt-5 flex flex-wrap gap-3"><button type="button" className="button-secondary" onClick={()=>{setActive(false);setScenario(createAidScenario(profile));setNotice('Scenario discarded. Saved profile unchanged.')}}>Exit without saving</button><button type="button" className="button-primary" disabled={comparison.scenario.status!=='calculated'} onClick={async()=>{if(comparison.scenario.status!=='calculated')return;await householdRepository.save({...scenario,isFictionalDemo:false});setNotice('Scenario applied and saved locally as the household profile.');setActive(false)}}>Apply and save scenario</button></div><p className="mt-3 min-h-6 text-sm font-bold text-moss-700" role="status">{notice}</p></section>
}

function ScenarioResults({comparison}:{comparison:ReturnType<typeof compareAidScenario>}){if(comparison.current.status!=='calculated')return null;if(comparison.scenario.status!=='calculated')return <div className="mt-5 rounded-lg bg-gold-100 p-4"><p className="font-bold">Scenario cannot be calculated</p><p className="mt-2 text-sm">The hypothetical inputs are incomplete or outside supported Formula A scope. No numeric scenario result is shown.</p></div>;const currentPell=comparison.current.pell.status==='eligible'?comparison.current.pell.scheduledAward:null,scenarioPell=comparison.scenario.pell.status==='eligible'?comparison.scenario.pell.scheduledAward:null;return <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[32rem] border-collapse text-left"><caption className="mb-3 text-left font-bold">Current profile compared with unsaved scenario</caption><thead><tr><th className="border-b p-3">Result</th><th className="border-b p-3">Current</th><th className="border-b p-3">Scenario</th><th className="border-b p-3">Change</th></tr></thead><tbody><tr><th className="p-3">SAI</th><td className="p-3">{comparison.current.sai.sai.toLocaleString()}</td><td className="p-3" data-testid="scenario-sai">{comparison.scenario.sai.sai.toLocaleString()}</td><td className="p-3">{signed(comparison.scenario.sai.sai-comparison.current.sai.sai,value=>value.toLocaleString())}</td></tr><tr><th className="p-3">Pell Scheduled Award estimate</th><td className="p-3">{currentPell===null?'Not eligible':money(currentPell)}</td><td className="p-3" data-testid="scenario-pell">{scenarioPell===null?'Not eligible':money(scenarioPell)}</td><td className="p-3">{currentPell!==null&&scenarioPell!==null?signed(scenarioPell-currentPell,money):'Path changed'}</td></tr><tr><th className="p-3">Pell path</th><td className="p-3">{comparison.current.pell.status==='eligible'?comparison.current.pell.eligibility:comparison.current.pell.status}</td><td className="p-3">{comparison.scenario.pell.status==='eligible'?comparison.scenario.pell.eligibility:comparison.scenario.pell.status}</td><td className="p-3">{comparison.current.pell.status===comparison.scenario.pell.status&&comparison.current.pell.status==='eligible'&&comparison.scenario.pell.status==='eligible'&&comparison.current.pell.eligibility===comparison.scenario.pell.eligibility?'No path change':'Review path'}</td></tr></tbody></table></div>}
function ScenarioNumber({label,value,change}:{label:string;value:number|null;change:(value:number|null)=>void}){return <label className="grid gap-2 text-sm font-bold">{label}<input className="min-h-11 rounded-lg border border-line px-3 font-normal" type="number" inputMode="decimal" step="any" value={value??''} placeholder="Unknown" onChange={event=>change(event.target.value===''?null:Number(event.target.value))}/></label>}
